import {describe,it,expect,vi} from 'vitest';
import type {IncomingMessage,ServerResponse} from 'node:http';
import {bibleSourceHandler} from './bible-source';
async function call(query:string,send:typeof fetch,method='GET',origin?:string){let status=0,headers:Record<string,string>={},body='';await bibleSourceHandler({url:'/?'+query,method,headers:{host:'ncg.test',...(origin?{origin}:{})}} as IncomingMessage,{writeHead(s:number,h:Record<string,string>){status=s;headers=h;},end(b:string){body=b;}} as unknown as ServerResponse,send);return{status,headers,body:JSON.parse(body)};}
describe('Bible source boundary',()=>{
 it('rejects unknown editions, restricted editions, traversal, arbitrary URLs and unsafe methods before fetching',async()=>{const send=vi.fn();for(const query of ['version=unknown&file=index.htm','version=spaLBLA&file=index.htm','version=spaRV1909&file=../secret','version=spaRV1909&file=https://evil.test','version=spaRV1909&file=JHN03.htm.js'])expect((await call(query,send)).status).toBe(400);expect((await call('version=spaRV1909&file=index.htm',send,'POST')).status).toBe(405);expect((await call('version=spaRV1909&file=index.htm',send,'GET','https://evil.test')).status).toBe(403);expect(send).not.toHaveBeenCalled();});
 it('returns publisher HTML as inert JSON, with a fixed upstream host and no redirects',async()=>{const send=vi.fn(async()=>new Response('<html><body>source</body></html>',{headers:{'content-type':'text/html'}})) as unknown as typeof fetch;const result=await call('version=spaRV1909&file=index.htm',send);expect(result.status).toBe(200);expect(result.headers['Content-Type']).toContain('application/json');expect(result.headers['X-Content-Type-Options']).toBe('nosniff');expect(send).toHaveBeenCalledWith('https://ebible.org/spaRV1909/index.htm',expect.objectContaining({redirect:'error'}));});
 it('accepts the upstream Nahum code and rejects chapters beyond its canonical range',async()=>{const send=vi.fn(async()=>new Response('<html><body>Nahum</body></html>',{headers:{'content-type':'text/html'}}));expect((await call('version=spaRV1909&file=NAM01.htm',send as typeof fetch)).status).toBe(200);expect(send).toHaveBeenCalledWith('https://ebible.org/spaRV1909/NAM01.htm',expect.anything());send.mockClear();expect((await call('version=spaRV1909&file=NAM04.htm',send as typeof fetch)).status).toBe(400);expect(send).not.toHaveBeenCalled();});
 it('rejects oversized upstream data and bad content types',async()=>{let send=vi.fn(async()=>new Response('x'.repeat(1500001),{headers:{'content-type':'text/html'}})) as unknown as typeof fetch;expect((await call('version=spaRV1909&file=JHN02.htm',send)).status).toBe(502);send=vi.fn(async()=>new Response('{}',{headers:{'content-type':'application/json'}})) as unknown as typeof fetch;expect((await call('version=spaRV1909&file=JHN02.htm',send)).status).toBe(502);});
});
