import{PGlite}from'@electric-sql/pglite';import{readFileSync}from'node:fs';import{beforeAll,afterAll,beforeEach,it,expect}from'vitest';
let db:PGlite;const A='00000000-0000-4000-8000-000000000001',B='00000000-0000-4000-8000-000000000002',C='00000000-0000-4000-8000-000000000003';
async function asUser<T>(id:string|null,sql:string,args:unknown[]=[]){await db.exec(id?'set role authenticated':'set role anon');try{await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id||'']);return await db.query<T>(sql,args);}finally{await db.exec('reset role');}}
async function claim(kind:string|null,id:string|null=null){return(await asUser<{claimed:boolean}>(id,'select ncg_claim_translation_budget($1) claimed',[kind])).rows[0].claimed;}
beforeAll(async()=>{db=new PGlite();await db.exec("create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid;$$;grant usage on schema auth,public to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;");for(const f of ['001_ncg_members.sql','011_ncg_translation_budget.sql'])await db.exec(readFileSync(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));for(const id of[A,B,C])await db.query('insert into auth.users values($1)',[id]);},20000);
beforeEach(async()=>{await db.exec('truncate ncg_translation_budget,ncg_suspensions');});afterAll(async()=>{await db?.close();});
it('reserves at most 60 Bible generations across all requesters',async()=>{for(let i=0;i<60;i++)expect(await claim('bible',i%2?A:null)).toBe(true);expect(await claim('bible',B)).toBe(false);expect((await db.query<{used:number}>("select used from ncg_translation_budget where subject='global'")).rows).toEqual([{used:60}]);});
it('limits each member and all guests separately without consuming a global slot on denial',async()=>{for(let i=0;i<20;i++)expect(await claim('community',A)).toBe(true);expect(await claim('community',A)).toBe(false);expect(await claim('community',B)).toBe(true);for(let i=0;i<20;i++)expect(await claim('community')).toBe(true);expect(await claim('community')).toBe(false);expect((await db.query<{used:number}>("select used from ncg_translation_budget where subject='global'")).rows[0].used).toBe(41);});
it('shares the global community ceiling across members',async()=>{for(const id of[A,B,C])for(let i=0;i<20;i++)expect(await claim('community',id)).toBe(true);expect(await claim('community')).toBe(false);});
it('rejects unknown budgets and suspended community members while keeping Bible access available',async()=>{for(const kind of[null,'custom','global'])await expect(claim(kind)).rejects.toThrow('invalid_budget');await db.query('insert into ncg_suspensions(user_id) values($1)',[A]);await expect(claim('community',A)).rejects.toThrow('not_authorized');expect(await claim('bible',A)).toBe(true);});
it('prevents callers from reading or resetting the budget or choosing another identity/date',async()=>{await claim('community',A);for(const id of[A,null])for(const sql of['select * from ncg_translation_budget','delete from ncg_translation_budget','update ncg_translation_budget set used=0'])await expect(asUser(id,sql)).rejects.toThrow('permission denied');});
it('uses the database day and prunes old counters without retaining text or credentials',async()=>{await db.exec("insert into ncg_translation_budget values('bible',(now() at time zone 'UTC')::date-15,'global',60),('bible',(now() at time zone 'UTC')::date-1,'global',60)");expect(await claim('bible')).toBe(true);expect((await db.query('select * from ncg_translation_budget')).rows).toHaveLength(2);});

it('carries legacy Bible usage forward but cannot reduce an existing reservation count',async()=>{
 expect((await asUser<{claimed:boolean}>(null,'select ncg_claim_translation_budget($1,$2) claimed',['bible',58])).rows[0].claimed).toBe(true);
 expect(await claim('bible')).toBe(true);expect(await claim('bible')).toBe(false);
 for(const floor of[-1,61,null])await expect(asUser(null,'select ncg_claim_translation_budget($1,$2)',['bible',floor])).rejects.toThrow('invalid_budget');
 await expect(asUser(A,'select ncg_claim_translation_budget($1,$2)',['community',1])).rejects.toThrow('invalid_budget');
});

it('persists a full legacy budget so a later lower floor cannot reopen it',async()=>{expect((await asUser<{claimed:boolean}>(null,'select ncg_claim_translation_budget($1,$2) claimed',['bible',60])).rows[0].claimed).toBe(false);expect(await claim('bible')).toBe(false);});
