import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Bookmark,BookOpen,ChevronDown,Globe,Search,Settings2,X} from 'lucide-react';
import {useApp} from '../state';
import {Modal} from '../components/Ui';
import {OfflineBible} from '../components/OfflineBible';
import {languageName} from '../core/languages';
import {adjacentChapter,preferredBibleVersion,isKoreanRevisedVersion,koreanRevisedLink,bibleRequest,chapterOf,defaultReader,readReaderPreferences,parsePassage,resolvePassage,safeBibleLink,type BibleBook,type BibleIndex,type BiblePassage,type BibleVersion,type ReaderPreferences} from '../core/bible';

function PassagePicker({index,passage,onSelect,onClose}:{index:BibleIndex;passage:string;onSelect:(id:string)=>void;onClose:()=>void}){
 const {t}=useApp();const [query,setQuery]=useState('');const [canon,setCanon]=useState('all');const [book,setBook]=useState<BibleBook|null>(index.books.find(b=>b.id===passage.split('.')[0])||null);const [chapter,setChapter]=useState<string|null>(null);
 const books=index.books.filter(b=>(canon==='all'||b.canon===canon)&&`${b.title} ${b.full_title} ${b.abbreviation} ${b.id}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const selectedChapter=book?.chapters.find(c=>c.passage_id===chapter);
 return <Modal wide title={t('성경 찾기','Find a passage')} onClose={onClose}>
  <div className="passage-steps"><button className={!book?'active':''} onClick={()=>{setBook(null);setChapter(null);}}>{t('성경','Book')}</button><span>›</span><button disabled={!book} className={book&&!chapter?'active':''} onClick={()=>setChapter(null)}>{book?.title||t('장','Chapter')}</button><span>›</span><span>{selectedChapter?t('절','Verse'):t('장 · 절 선택','Chapter · Verse')}</span></div>
  {!book?<><label className="search-box"><Search size={17}/><input aria-label={t("성경 이름 검색","Search Bible books")} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('성경 이름 검색','Search a book')} autoFocus/></label><div className="tabs">{[['all',t('전체','All')],['old_testament',t('구약','Old Testament')],['new_testament',t('신약','New Testament')]].map(([id,label])=><button key={id} className={canon===id?'active':''} onClick={()=>setCanon(id)}>{label}</button>)}</div><div className="bible-book-grid">{books.map(b=><button key={b.id} onClick={()=>setBook(b)}><b dir="auto">{b.title}</b><small>{b.chapters.length} {t('장','chapters')}</small></button>)}</div>{books.length===0&&<p className="muted">{t('일치하는 성경이 없습니다.','No matching books.')}</p>}</>:!chapter?<><h3 dir="auto">{book.title}</h3><p className="muted">{t('장을 선택한 뒤 전체 장 또는 원하는 절로 이동하세요.','Choose a chapter, then read the whole chapter or a specific verse.')}</p><div className="chapter-grid">{book.chapters.map(c=><button className={chapterOf(passage)===c.passage_id?'selected':''} key={c.passage_id} onClick={()=>setChapter(c.passage_id)}>{c.title}</button>)}</div></>:<><div className="section-head"><h3 dir="auto">{book.title} {selectedChapter?.title}</h3><button className="button" onClick={()=>onSelect(chapter)}>{t('장 전체 읽기','Read chapter')}<ArrowRight size={16}/></button></div><div className="chapter-grid">{selectedChapter?.verses.map(v=><button key={v.passage_id} onClick={()=>onSelect(v.passage_id)}>{v.title}</button>)}</div></>}
 </Modal>;
}

export default function Bible({onLanguage}:{onLanguage:()=>void}){
 const {state,t}=useApp();const [readingOverride,setReadingOverride]=useState(()=>{const code=new URLSearchParams(location.hash.split('?')[1]).get('language');try{return code?Intl.getCanonicalLocales(code)[0]:'';}catch{return '';}});const readingLanguage=readingOverride||state.language;const changeLanguage=()=>{setReadingOverride('');onLanguage();};const [preferences,setPreferences]=useState<ReaderPreferences>(()=>{try{const stored=readReaderPreferences(JSON.parse(localStorage.getItem('ncg:reader:v1')||'null'));const requested=new URLSearchParams(location.hash.split('?')[1]).get('passage');return requested&&parsePassage(requested)?{...stored,passage:requested}:stored;}catch{return structuredClone(defaultReader);}});
 const [versions,setVersions]=useState<BibleVersion[]>([]);const [catalogueError,setCatalogueError]=useState('');const [providerStatus,setProviderStatus]=useState('');const [loading,setLoading]=useState(true);const [retry,setRetry]=useState(0);
 const [versionId,setVersionId]=useState('');const [index,setIndex]=useState<BibleIndex|null>(null);const [text,setText]=useState<BiblePassage|null>(null);const [readingError,setReadingError]=useState('');const [reading,setReading]=useState(false);const [picker,setPicker]=useState(false);const [settings,setSettings]=useState(false);const [savedOpen,setSavedOpen]=useState(false);const [saveError,setSaveError]=useState(false);
 const priorLanguage=useRef(state.language);useEffect(()=>{if(priorLanguage.current!==state.language){setReadingOverride('');priorLanguage.current=state.language;}},[state.language]);
 const version=versions.find(v=>String(v.id)===versionId);const passage=preferences.passage;
 useEffect(()=>{try{localStorage.setItem('ncg:reader:v1',JSON.stringify(preferences));setSaveError(false);}catch{setSaveError(true);}},[preferences]);
 useEffect(()=>{
  const controller=new AbortController();setLoading(true);setVersions([]);setVersionId('');setIndex(null);setText(null);setCatalogueError('');setProviderStatus('');
  bibleRequest<{data:BibleVersion[];providerStatus?:string}>('versions',{language:readingLanguage},controller.signal).then(result=>{if(controller.signal.aborted)return;setVersions(result.data);setProviderStatus(result.providerStatus||'');const requestedVersion=new URLSearchParams(location.hash.split('?')[1]).get('version');const preferred=requestedVersion||preferences.versions[readingLanguage];setVersionId(String(preferredBibleVersion(result.data,readingLanguage,preferred)?.id||''));}).catch(e=>{if(!controller.signal.aborted)setCatalogueError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
  return()=>controller.abort();
 },[readingLanguage,retry]);
 useEffect(()=>{
  if(!versionId)return;const controller=new AbortController();setIndex(null);setText(null);setReadingError('');
  bibleRequest<BibleIndex>('index',{version:versionId},controller.signal).then(data=>{if(controller.signal.aborted)return;setIndex(data);const chapters=data.books.flatMap(b=>b.chapters);setPreferences(p=>({...p,versions:{...p.versions,[readingLanguage]:versionId},passage:resolvePassage(data,p.passage)}));}).catch(e=>{if(!controller.signal.aborted)setReadingError(e.message);});
  return()=>controller.abort();
 },[versionId,retry]);
 useEffect(()=>{
  if(!index||!versionId)return;const controller=new AbortController();setText(null);setReading(true);setReadingError('');
  bibleRequest<BiblePassage>('passage',{version:versionId,passage},controller.signal).then(data=>{if(!controller.signal.aborted)setText(data);}).catch(e=>{if(!controller.signal.aborted)setReadingError(e.message);}).finally(()=>{if(!controller.signal.aborted)setReading(false);});
  return()=>controller.abort();
 },[index,versionId,passage,retry]);
 const currentBook=index?.books.find(b=>b.id===passage.split('.')[0]);const currentChapter=currentBook?.chapters.find(c=>c.passage_id===chapterOf(passage));
 const previous=index?adjacentChapter(index,passage,-1):null;const next=index?adjacentChapter(index,passage,1):null;
 const bookmarked=preferences.bookmarks.some(b=>String(b.version)===versionId&&b.passage===passage);
 const reference=text?.reference||`${currentBook?.title||''} ${currentChapter?.title||''}`.trim();
 const publisher=safeBibleLink(version?.publisher_url);const source=safeBibleLink(version?.youversion_deep_link);
 function go(id:string){setPreferences(p=>({...p,passage:id}));setPicker(false);window.scrollTo({top:0,behavior:'smooth'});}
 function bookmark(){if(!text||!version)return;setPreferences(p=>({...p,bookmarks:bookmarked?p.bookmarks.filter(b=>!(String(b.version)===versionId&&b.passage===passage)):[{version:versionId,passage,reference:text.reference,language:readingLanguage},...p.bookmarks].slice(0,300)}));}
 const bookmarkItems=useMemo(()=>preferences.bookmarks.filter(b=>b.language===readingLanguage),[preferences.bookmarks,readingLanguage]);
 return <>
  <div className="page-heading bible-heading"><span className="eyebrow">{t("성경 말씀","THE HOLY BIBLE")}</span><h1>{t('말씀 가까이','Closer to the Word')}</h1><p>{t('성경을 찾고, 천천히 읽고, 마음에 새겨보세요.','Find a passage. Read with care. Keep it in your heart.')}</p></div>
  {readingLanguage.split('-')[0]==='ko'&&!versions.some(isKoreanRevisedVersion)&&<div className="korean-bible-notice"><BookOpen size={22}/><div><b>{t('개역개정 성경','New Korean Revised Version')}</b><p>{t('개역개정은 한국어 기본 역본으로 준비하고 있습니다. 앱 내 본문 연결 전에는 대한성서공회에서 읽을 수 있습니다.','NKRV is our planned default Korean version. Until the licensed text is connected, read it on the Korean Bible Society website.')}</p><a className="text-link" href={koreanRevisedLink(passage)} target="_blank" rel="noreferrer">{t('대한성서공회에서 개역개정 읽기','Read NKRV at the Korean Bible Society')} ↗</a></div></div>}
  <OfflineBible/>
  <section className={`bible-reader reader-${preferences.theme}`} aria-label={t('성경 읽기','Bible reader')}>
   <div className="reader-toolbar"><button className="reader-passage-button" onClick={()=>setPicker(true)} disabled={!index}><BookOpen size={20}/><span>{reference||t('성경 · 장 · 절','Book · Chapter · Verse')}</span><ChevronDown size={16}/></button><div className="reader-tools"><button className="icon-button" onClick={()=>setSavedOpen(true)} aria-label={t('보관한 성경 구절','Saved passages')}><Bookmark size={19}/></button><button className="icon-button" onClick={()=>setSettings(!settings)} aria-label={t('읽기 설정','Reading settings')} aria-expanded={settings}><Settings2 size={19}/></button></div></div>
   <div className="reader-version-row"><button className="text-link" onClick={changeLanguage}><Globe size={16}/>{languageName(readingLanguage,state.ui)}<ChevronDown size={14}/></button><label><span className="sr-only">{t('성경 역본','Bible version')}</span><select disabled={!versions.length} value={versionId} onChange={e=>setVersionId(e.target.value)}>{!versions.length&&<option value="">{loading?t('역본 불러오는 중…','Loading versions…'):t('역본 연결 대기','No version connected')}</option>}{versions.map(v=><option key={v.id} value={v.id}>{v.localized_title||v.title} ({v.localized_abbreviation||v.abbreviation})</option>)}</select></label></div>
   {providerStatus&&<p className="reader-provider-note">{t("WEB 영어 성경을 먼저 제공합니다. 다른 역본 목록은 연결 중입니다.","WEB is available now. The additional version catalogue is being connected.")}</p>}{settings&&<div className="reader-settings"><fieldset><legend>{t('글자 크기','Text size')}</legend><button disabled={preferences.fontSize<=16} onClick={()=>setPreferences(p=>({...p,fontSize:p.fontSize-2}))} aria-label={t('글자 작게','Smaller text')}>A−</button><span>{preferences.fontSize}</span><button disabled={preferences.fontSize>=30} onClick={()=>setPreferences(p=>({...p,fontSize:p.fontSize+2}))} aria-label={t('글자 크게','Larger text')}>A+</button></fieldset><fieldset><legend>{t('읽기 배경','Reading background')}</legend>{[['light',t('밝게','Light')],['warm',t('따뜻하게','Warm')],['dark',t('어둡게','Dark')]].map(([id,label])=><button key={id} aria-pressed={preferences.theme===id} onClick={()=>setPreferences(p=>({...p,theme:id as ReaderPreferences['theme']}))}>{label}</button>)}</fieldset></div>}
   {loading?<div className="reader-empty" role="status"><BookOpen size={32}/><h2>{t('내 언어의 성경을 찾고 있어요.','Finding Bibles in your language.')}</h2></div>:catalogueError||!versions.length?<div className="reader-empty"><BookOpen size={38} strokeWidth={1.3}/><h2>{catalogueError==='bible_not_configured'?t('정식 성경 역본을 연결하고 있습니다.','Bible versions are being connected.'):catalogueError?t('성경 목록을 불러오지 못했습니다.','Unable to load Bible versions.'):t('이 언어의 역본을 준비하고 있습니다.','A Bible in your language is being prepared.')}</h2><p>{t('사용이 허가된 역본의 본문과 출판사 정보를 함께 제공합니다. 준비되지 않은 본문을 임의 번역하여 성경으로 표시하지 않습니다.','Available versions include their publisher and source. We do not substitute generated translations for Scripture.')}</p><div className="button-row"><button className="button secondary" onClick={changeLanguage}>{t('다른 언어 선택','Choose another language')}</button>{catalogueError&&catalogueError!=='bible_not_configured'&&<button className="button secondary" onClick={()=>setRetry(n=>n+1)}>{t('다시 시도','Try again')}</button>}<a className="text-link" href="https://www.bible.com/languages" target="_blank" rel="noreferrer">{t('YouVersion에서 성경 읽기','Read on YouVersion')} ↗</a></div></div>:readingError?<div className="reader-empty" role="alert"><h2>{t('이 본문을 불러오지 못했습니다.','This passage could not be loaded.')}</h2><p>{t('연결을 확인하거나 다른 역본을 선택해주세요.','Check your connection or choose another version.')}</p><button className="button secondary" onClick={()=>setRetry(n=>n+1)}>{t('다시 시도','Try again')}</button></div>:reading||!text?<div className="reader-empty" role="status">{t('말씀을 불러오고 있습니다.','Loading the passage…')}</div>:<>
    <article className="scripture-page" lang={version?.language_tag} dir={index?.text_direction||'auto'} style={{fontSize:preferences.fontSize}}><div className="scripture-heading"><div><span className="eyebrow">{version?.localized_abbreviation||version?.abbreviation}</span><h2>{text.reference}</h2></div><button className={`icon-button ${bookmarked?'saved':''}`} onClick={bookmark} aria-label={bookmarked?t('책갈피 해제','Remove bookmark'):t('책갈피 저장','Bookmark passage')} aria-pressed={bookmarked}><Bookmark size={22} fill={bookmarked?'currentColor':'none'}/></button></div><div className="scripture-text">{text.verses?text.verses.map(v=><section className="verse-unit" key={v.id}>{v.heading&&<h3>{v.heading}</h3>}<p className="scripture-verse"><sup>{v.number}</sup><span>{v.text}</span></p>{v.notes?.length&&<details className="verse-notes"><summary>{t("각주","Notes")} {v.number}</summary>{v.notes.map((note,i)=><p key={i}>{note}</p>)}</details>}</section>):text.content}</div>{passage!==chapterOf(passage)&&<button className="text-link" onClick={()=>go(chapterOf(passage))}>{t('이 장 전체 읽기','Read the full chapter')}<ArrowRight size={16}/></button>}</article>
    <div className="reader-chapter-nav"><button className="text-link" disabled={!previous} onClick={()=>previous&&go(previous)}><ArrowLeft size={17}/>{t('이전 장','Previous chapter')}</button><button className="text-link" onClick={()=>setPicker(true)}>{t('성경 찾기','Find a passage')}</button><button className="text-link" disabled={!next} onClick={()=>next&&go(next)}>{t('다음 장','Next chapter')}<ArrowRight size={17}/></button></div>
    <div className="bible-attribution"><b>{version?.localized_title||version?.title}</b><p>{version?.copyright}</p>{version?.info&&<p>{version.info}</p>}<div>{publisher&&<a href={publisher} target="_blank" rel="noreferrer">{t('출판사 안내','Publisher')} ↗</a>}{source&&<a href={source} target="_blank" rel="noreferrer">{t('본문 출처','Source')} ↗</a>}</div></div>
   </>}
  </section>
  {saveError&&<p className="error" role="alert">{t('이 브라우저에서 읽기 설정을 저장하지 못했습니다.','Reading preferences could not be saved in this browser.')}</p>}
  <a className="reader-qt-link" href="#/qt"><span><b>{t('읽은 말씀을 삶으로','From Scripture into life')}</b><small>{t('전 세계 QT에서 함께 묵상해요.','Reflect together in Global QT.')}</small></span><ArrowRight size={20}/></a>
  {picker&&index&&<PassagePicker index={index} passage={passage} onSelect={go} onClose={()=>setPicker(false)}/>}
  {savedOpen&&<Modal title={t('보관한 성경 구절','Saved passages')} onClose={()=>setSavedOpen(false)}>{bookmarkItems.length?<div className="saved-passages">{bookmarkItems.map(b=><div key={`${b.version}:${b.passage}`}><button onClick={()=>{setVersionId(String(b.version));go(b.passage);setSavedOpen(false);}} disabled={!versions.some(v=>String(v.id)===String(b.version))}><BookOpen size={17}/><span>{b.reference}<small>{versions.find(v=>String(v.id)===String(b.version))?.abbreviation||t('현재 연결되지 않은 역본','Version currently unavailable')}</small></span><ArrowRight size={16}/></button><button className="icon-button" aria-label={t('책갈피 해제','Remove bookmark')} onClick={()=>setPreferences(p=>({...p,bookmarks:p.bookmarks.filter(x=>!(x.version===b.version&&x.passage===b.passage))}))}><X size={17}/></button></div>)}</div>:<p className="muted">{t('읽다가 마음에 남은 구절에 책갈피를 남겨보세요. 현재 언어의 책갈피가 여기에 모입니다.','Bookmark a passage as you read. Bookmarks in your current language appear here.')}</p>}</Modal>}
 </>;
}
