import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Bookmark,BookOpen,ChevronDown,Globe,Settings2,X} from 'lucide-react';
import {useApp} from '../state';
import {Modal} from '../components/Ui';
import {BibleTranslationAssist} from '../components/BibleTranslationAssist';
import {BibleNavigator} from '../components/BibleNavigator';
import {OfflineBible} from '../components/OfflineBible';
import {languageName} from '../core/languages';
import {webVersion,adjacentChapter,verseInSelection,navigateBibleChapter,preferredBibleVersion,isKoreanRevisedVersion,koreanRevisedLink,bibleRequest,chapterOf,defaultReader,readReaderPreferences,parsePassage,resolvePassage,safeBibleLink,type BibleIndex,type BibleChapter,type BiblePassage,type BibleVersion,type ReaderPreferences} from '../core/bible';

export default function Bible({onLanguage}:{onLanguage:()=>void}){
 const {state,t}=useApp();const [readingOverride,setReadingOverride]=useState(()=>{const code=new URLSearchParams(location.hash.split('?')[1]).get('language');try{return code?Intl.getCanonicalLocales(code)[0]:'';}catch{return '';}});const readingLanguage=readingOverride||state.language;const changeLanguage=()=>{setReadingOverride('');onLanguage();};const [preferences,setPreferences]=useState<ReaderPreferences>(()=>{try{const stored=readReaderPreferences(JSON.parse(localStorage.getItem('ncg:reader:v1')||'null'));const requested=new URLSearchParams(location.hash.split('?')[1]).get('passage');return requested&&parsePassage(requested)?{...stored,passage:requested}:stored;}catch{return structuredClone(defaultReader);}});
 const [referenceTranslation,setReferenceTranslation]=useState(false);const [versions,setVersions]=useState<BibleVersion[]>([]);const [catalogueError,setCatalogueError]=useState('');const [providerStatus,setProviderStatus]=useState('');const [loading,setLoading]=useState(true);const [retry,setRetry]=useState(0);
 const [versionId,setVersionId]=useState('');const [index,setIndex]=useState<BibleIndex|null>(null);const [text,setText]=useState<BiblePassage|null>(null);const [readingError,setReadingError]=useState('');const [reading,setReading]=useState(false);const [picker,setPicker]=useState(false);const [settings,setSettings]=useState(false);const [savedOpen,setSavedOpen]=useState(false);const [saveError,setSaveError]=useState(false);
 const navigating=useRef<AbortController|null>(null);useEffect(()=>()=>navigating.current?.abort(),[versionId]);
 const priorLanguage=useRef(state.language);useEffect(()=>{if(priorLanguage.current!==state.language){setReadingOverride('');priorLanguage.current=state.language;}},[state.language]);
 const version=versions.find(v=>String(v.id)===versionId);const passage=preferences.passage;const readingChapter=chapterOf(passage);const readerRef=useRef<HTMLElement>(null);const scrollRequest=useRef(false);const [navigation,setNavigation]=useState(0);
 useEffect(()=>{try{localStorage.setItem('ncg:reader:v1',JSON.stringify(preferences));setSaveError(false);}catch{setSaveError(true);}},[preferences]);
 useEffect(()=>{
  const controller=new AbortController();setLoading(true);setReferenceTranslation(false);setVersions([]);setVersionId('');setIndex(null);setText(null);setCatalogueError('');setProviderStatus('');
  bibleRequest<{data:BibleVersion[];providerStatus?:string}>('versions',{language:readingLanguage},controller.signal).then(result=>{if(controller.signal.aborted)return;const editions=result.data.length?result.data:[webVersion];setReferenceTranslation(!result.data.length);setVersions(editions);setProviderStatus(result.providerStatus||'');const requestedVersion=new URLSearchParams(location.hash.split('?')[1]).get('version');const preferred=requestedVersion||preferences.versions[readingLanguage];setVersionId(String(preferredBibleVersion(editions,readingLanguage,preferred)?.id||''));}).catch(e=>{if(!controller.signal.aborted)setCatalogueError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
  return()=>controller.abort();
 },[readingLanguage,retry]);
 useEffect(()=>{
  if(!versionId)return;const controller=new AbortController();setIndex(null);setText(null);setReadingError('');if(version?.access==='external')return;
  bibleRequest<BibleIndex>('index',{version:versionId,passage},controller.signal).then(data=>{if(controller.signal.aborted)return;setIndex(data);setPreferences(p=>({...p,versions:{...p.versions,[readingLanguage]:versionId},passage:resolvePassage(data,p.passage)}));}).catch(e=>{if(!controller.signal.aborted){if(import.meta.env.DEV)console.warn('Bible reading failed',e);setReadingError(e.message);}});
  return()=>controller.abort();
 },[versionId,retry]);
 useEffect(()=>{
  if(!index||!versionId||version?.access==='external')return;const controller=new AbortController();setText(null);setReading(true);setReadingError('');
  bibleRequest<BiblePassage>('passage',{version:versionId,passage:readingChapter},controller.signal).then(data=>{if(controller.signal.aborted)return;setText(data);if(data.verses)setIndex(previous=>previous?{...previous,books:previous.books.map(b=>({...b,chapters:b.chapters.map(c=>c.passage_id===readingChapter&&c.versesKnown===false?{...c,versesKnown:true,verses:data.verses!.map(v=>({id:v.number,title:v.label||v.number,passage_id:v.id}))}:c)}))}:previous);}).catch(e=>{if(!controller.signal.aborted){if(import.meta.env.DEV)console.warn('Bible reading failed',e);setReadingError(e.message);}}).finally(()=>{if(!controller.signal.aborted)setReading(false);});
  return()=>controller.abort();
 },[!!index,versionId,readingChapter,retry]);
 useEffect(()=>{if(!scrollRequest.current||picker||!text||chapterOf(text.id)!==readingChapter)return;const target=readerRef.current?.querySelector<HTMLElement>('[data-verse-selected="true"]')||readerRef.current;target?.scrollIntoView({block:'center',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});target?.focus({preventScroll:true});scrollRequest.current=false;},[text,passage,picker,navigation,readingChapter]);
 const bookCode=passage.split('.')[0];const chaptersKnown=index?.books.find(b=>b.id===bookCode)?.chaptersKnown;
 useEffect(()=>{if(!index||chaptersKnown!==false)return;const controller=new AbortController();bibleRequest<BibleChapter[]>('book',{version:versionId,book:bookCode},controller.signal).then(chapters=>{if(controller.signal.aborted)return;setIndex(previous=>previous?{...previous,books:previous.books.map(b=>b.id===bookCode?{...b,chaptersKnown:true,chapters:chapters.map(c=>{const existing=b.chapters.find(old=>old.passage_id===c.passage_id);return existing?.versesKnown?{...c,verses:existing.verses,versesKnown:true}:c;})}:b)}:previous);}).catch(e=>{if(!controller.signal.aborted){if(import.meta.env.DEV)console.warn('Bible reading failed',e);setReadingError(e.message);}});return()=>controller.abort();},[versionId,bookCode,chaptersKnown,retry]);
 const currentBook=index?.books.find(b=>b.id===passage.split('.')[0]);const currentChapter=currentBook?.chapters.find(c=>c.passage_id===chapterOf(passage));
 const previous=index?adjacentChapter(index,passage,-1):null;const next=index?adjacentChapter(index,passage,1):null;
 const bookmarked=preferences.bookmarks.some(b=>String(b.version)===versionId&&b.passage===passage);
 const reference=text?`${text.reference}${parsePassage(passage)?.from?`:${passage.split('.')[2]}`:''}`:`${currentBook?.title||''} ${currentChapter?.title||''}`.trim();
 const publisher=safeBibleLink(version?.publisher_url);const source=safeBibleLink(version?.youversion_deep_link);
 function go(id:string,close=true){navigating.current?.abort();scrollRequest.current=true;setPreferences(p=>({...p,passage:id}));setNavigation(n=>n+1);if(close)setPicker(false);}
 async function adjacent(step:-1|1){if(!index)return;navigating.current?.abort();const controller=new AbortController();navigating.current=controller;try{const result=await navigateBibleChapter(index,passage,step,book=>bibleRequest<BibleChapter[]>('book',{version:versionId,book},controller.signal));if(result&&!controller.signal.aborted){setIndex(result.index);go(result.passage);}}catch(e){if(!controller.signal.aborted)setReadingError(e instanceof Error?e.message:'bible_unavailable');}}
 function bookmark(){if(!text||!version)return;setPreferences(p=>({...p,bookmarks:bookmarked?p.bookmarks.filter(b=>!(String(b.version)===versionId&&b.passage===passage)):[{version:versionId,passage,reference,language:readingLanguage},...p.bookmarks].slice(0,300)}));}
 const bookmarkItems=useMemo(()=>preferences.bookmarks.filter(b=>b.language===readingLanguage),[preferences.bookmarks,readingLanguage]);
 return <>
  <div className="page-heading bible-heading"><span className="eyebrow">{t("성경 말씀","THE HOLY BIBLE")}</span><h1>{t('말씀 가까이','Closer to the Word')}</h1><p>{t('성경을 찾고, 천천히 읽고, 마음에 새겨보세요.','Find a passage. Read with care. Keep it in your heart.')}</p></div>
  {readingLanguage.split('-')[0]==='ko'&&!versions.some(v=>isKoreanRevisedVersion(v)&&v.access!=='external')&&<div className="korean-bible-notice"><BookOpen size={22}/><div><b>{t('개역개정 성경','New Korean Revised Version')}</b><p>{t('개역개정은 한국어 기본 역본으로 준비하고 있습니다. 앱 내 본문 연결 전에는 대한성서공회에서 읽을 수 있습니다.','NKRV is our planned default Korean version. Until the licensed text is connected, read it on the Korean Bible Society website.')}</p><a className="text-link" href={koreanRevisedLink(passage)} target="_blank" rel="noreferrer">{t('대한성서공회에서 개역개정 읽기','Read NKRV at the Korean Bible Society')} ↗</a></div></div>}
  <OfflineBible/>
  <div className={`bible-workspace ${index?'has-navigator':''}`}><aside className="bible-desktop-nav" aria-label={t('성경 찾기','Find a passage')}>{index&&<BibleNavigator index={index} passage={passage} onSelect={go}/>}</aside>
  <section ref={readerRef} tabIndex={-1} className={`bible-reader reader-${preferences.theme}`} aria-label={t('성경 읽기','Bible reader')}>
   <div className="reader-toolbar"><button className="reader-passage-button" onClick={()=>setPicker(true)} disabled={!index}><BookOpen size={20}/><span>{reference||t('성경 · 장 · 절','Book · Chapter · Verse')}</span><ChevronDown size={16}/></button><div className="reader-tools"><button className="icon-button" onClick={()=>setSavedOpen(true)} aria-label={t('보관한 성경 구절','Saved passages')}><Bookmark size={19}/></button><button className="icon-button" onClick={()=>setSettings(!settings)} aria-label={t('읽기 설정','Reading settings')} aria-expanded={settings}><Settings2 size={19}/></button></div></div>
   <div className="reader-version-row"><button className="text-link" onClick={changeLanguage}><Globe size={16}/><span>{languageName(readingLanguage,state.ui)}</span><ChevronDown size={14}/></button><label><span className="sr-only">{t('성경 역본','Bible version')}</span><select disabled={!versions.length} value={versionId} onChange={e=>setVersionId(e.target.value)}>{!versions.length&&<option value="">{loading?t('역본 불러오는 중…','Loading versions…'):t('역본 연결 대기','No version connected')}</option>}{versions.map(v=><option key={v.id} value={v.id}>{v.localized_title||v.title} ({v.localized_abbreviation||v.abbreviation})</option>)}</select></label></div>
   {providerStatus&&<p className="reader-provider-note">{t("공개 역본과 제공처를 먼저 안내합니다. 추가 제휴 역본은 연결 중입니다.","Open editions and source links are available. Additional partner editions are being connected.")}</p>}{settings&&<div className="reader-settings"><fieldset><legend>{t('글자 크기','Text size')}</legend><button disabled={preferences.fontSize<=16} onClick={()=>setPreferences(p=>({...p,fontSize:p.fontSize-2}))} aria-label={t('글자 작게','Smaller text')}>A−</button><span>{preferences.fontSize}</span><button disabled={preferences.fontSize>=30} onClick={()=>setPreferences(p=>({...p,fontSize:p.fontSize+2}))} aria-label={t('글자 크게','Larger text')}>A+</button></fieldset><fieldset><legend>{t('읽기 배경','Reading background')}</legend>{[['light',t('밝게','Light')],['warm',t('따뜻하게','Warm')],['dark',t('어둡게','Dark')]].map(([id,label])=><button key={id} aria-pressed={preferences.theme===id} onClick={()=>setPreferences(p=>({...p,theme:id as ReaderPreferences['theme']}))}>{label}</button>)}</fieldset></div>}
   {loading?<div className="reader-empty" role="status"><BookOpen size={32}/><h2>{t('내 언어의 성경을 찾고 있어요.','Finding Bibles in your language.')}</h2></div>:catalogueError||!versions.length?<div className="reader-empty"><BookOpen size={38} strokeWidth={1.3}/><h2>{catalogueError==='bible_not_configured'?t('정식 성경 역본을 연결하고 있습니다.','Bible versions are being connected.'):catalogueError?t('성경 목록을 불러오지 못했습니다.','Unable to load Bible versions.'):t('이 언어의 역본을 준비하고 있습니다.','A Bible in your language is being prepared.')}</h2><p>{t('연결 가능한 정식 역본을 먼저 찾습니다. 영어 기반 자동번역은 원문과 구분하여 제공할 예정입니다.','We look for a published translation first. English-based automatic translation will be clearly distinguished from the source text.')}</p><div className="button-row"><button className="button secondary" onClick={changeLanguage}>{t('다른 언어 선택','Choose another language')}</button>{catalogueError&&catalogueError!=='bible_not_configured'&&<button className="button secondary" onClick={()=>setRetry(n=>n+1)}>{t('다시 시도','Try again')}</button>}<a className="text-link" href="https://www.bible.com/languages" target="_blank" rel="noreferrer">{t('YouVersion에서 성경 읽기','Read on YouVersion')} ↗</a></div></div>:version?.access==='external'?<div className="reader-empty"><BookOpen size={36}/><h2 dir="auto">{version.localized_title||version.title}</h2><p>{t('이 역본은 제공처에서 읽을 수 있습니다. 앱 내 본문 이용은 별도 연결이 필요합니다.','Read this edition at its source. In-app access requires an additional connection.')}</p>{source&&<a className="button" href={isKoreanRevisedVersion(version)?koreanRevisedLink(passage):source} target="_blank" rel="noreferrer">{t('제공처에서 읽기','Read at the source')} ↗</a>}<p>{version.copyright}</p></div>:readingError?<div className="reader-empty" role="alert"><h2>{t('이 본문을 불러오지 못했습니다.','This passage could not be loaded.')}</h2><p>{t('연결을 확인하거나 다른 역본을 선택해주세요.','Check your connection or choose another version.')}</p><button className="button secondary" onClick={()=>setRetry(n=>n+1)}>{t('다시 시도','Try again')}</button>{source&&<a className="text-link" href={source} target="_blank" rel="noreferrer">{t('제공처에서 읽기','Read at the source')} ↗</a>}</div>:reading||!text?<div className="reader-empty" role="status">{t('말씀을 불러오고 있습니다.','Loading the passage…')}</div>:<>
    <article className="scripture-page" lang={version?.language_tag} dir={index?.text_direction||'auto'} style={{fontSize:preferences.fontSize}}><div className="scripture-heading"><div><span className="eyebrow">{version?.localized_abbreviation||version?.abbreviation}</span><h2>{text.reference}</h2></div><button className={`icon-button ${bookmarked?'saved':''}`} onClick={bookmark} aria-label={bookmarked?t('책갈피 해제','Remove bookmark'):t('책갈피 저장','Bookmark passage')} aria-pressed={bookmarked}><Bookmark size={22} fill={bookmarked?'currentColor':'none'}/></button></div>{referenceTranslation&&<BibleTranslationAssist key={`${readingLanguage}:${text.id}`} language={readingLanguage} source={text} selected={passage}/>}<div className="scripture-text">{text.verses?text.verses.map(v=><section className={`verse-unit ${verseInSelection(passage,v.number)?'verse-selected':''}`} data-verse-selected={verseInSelection(passage,v.number)||undefined} tabIndex={-1} key={v.id}>{v.heading&&<h3>{v.heading}</h3>}<p className="scripture-verse"><sup>{v.label||v.number}</sup><span>{v.text}</span></p>{v.notes?.length&&<details className="verse-notes"><summary>{t("각주","Notes")} {v.number}</summary>{v.notes.map((note,i)=><p key={i}>{note}</p>)}</details>}</section>):text.content}</div>{passage!==chapterOf(passage)&&<button className="text-link" onClick={()=>go(chapterOf(passage))}>{t('이 장 전체 읽기','Read the full chapter')}<ArrowRight size={16}/></button>}</article>
    <div className="reader-chapter-nav"><button className="text-link" disabled={!previous} onClick={()=>void adjacent(-1)}><ArrowLeft size={17}/>{t('이전 장','Previous chapter')}</button><button className="text-link" onClick={()=>setPicker(true)}>{t('성경 찾기','Find a passage')}</button><button className="text-link" disabled={!next} onClick={()=>void adjacent(1)}>{t('다음 장','Next chapter')}<ArrowRight size={17}/></button></div>
    <div className="bible-attribution"><b>{version?.localized_title||version?.title}</b><p>{version?.copyright}</p>{version?.info&&<p>{version.info}</p>}{index?.license&&<details><summary>{t('이 역본의 이용 안내','Edition terms')}</summary><p dir="auto">{index.license}</p></details>}<div>{publisher&&<a href={publisher} target="_blank" rel="noreferrer">{t('출판사 안내','Publisher')} ↗</a>}{source&&<a href={source} target="_blank" rel="noreferrer">{t('본문 출처','Source')} ↗</a>}</div></div>
   </>}
  </section></div>
  {saveError&&<p className="error" role="alert">{t('이 브라우저에서 읽기 설정을 저장하지 못했습니다.','Reading preferences could not be saved in this browser.')}</p>}
  <a className="reader-qt-link" href="#/qt"><span><b>{t('읽은 말씀을 삶으로','From Scripture into life')}</b><small>{t('전 세계 QT에서 함께 묵상해요.','Reflect together in Global QT.')}</small></span><ArrowRight size={20}/></a>
  {picker&&index&&<Modal wide title={t('성경 찾기','Find a passage')} onClose={()=>setPicker(false)}><BibleNavigator index={index} passage={passage} onSelect={id=>go(id,false)} onRead={()=>setPicker(false)}/></Modal>}
  {savedOpen&&<Modal title={t('보관한 성경 구절','Saved passages')} onClose={()=>setSavedOpen(false)}>{bookmarkItems.length?<div className="saved-passages">{bookmarkItems.map(b=><div key={`${b.version}:${b.passage}`}><button onClick={()=>{setVersionId(String(b.version));go(b.passage);setSavedOpen(false);}} disabled={!versions.some(v=>String(v.id)===String(b.version))}><BookOpen size={17}/><span>{b.reference}<small>{versions.find(v=>String(v.id)===String(b.version))?.abbreviation||t('현재 연결되지 않은 역본','Version currently unavailable')}</small></span><ArrowRight size={16}/></button><button className="icon-button" aria-label={t('책갈피 해제','Remove bookmark')} onClick={()=>setPreferences(p=>({...p,bookmarks:p.bookmarks.filter(x=>!(x.version===b.version&&x.passage===b.passage))}))}><X size={17}/></button></div>)}</div>:<p className="muted">{t('읽다가 마음에 남은 구절에 책갈피를 남겨보세요. 현재 언어의 책갈피가 여기에 모입니다.','Bookmark a passage as you read. Bookmarks in your current language appear here.')}</p>}</Modal>}
 </>;
}
