import {useState} from 'react';
import {Globe,Heart,PenLine,ArrowUpRight} from 'lucide-react';
import {useApp} from '../state';
import {Compose} from '../components/Sharing';
import {SharedFeed} from '../components/SharedFeed';
import {supabase} from '../auth';
import {languageName} from '../core/languages';
export default function Community({onLanguage}:{onLanguage:()=>void}){
 const {state,t}=useApp();const [compose,setCompose]=useState(false);const [filter,setFilter]=useState('all');const [refresh,setRefresh]=useState(0);
 return <><div className="page-heading"><span className="eyebrow">{t("한 몸, 서로의 이야기","ONE BODY. MANY STORIES.")}</span><h1>{t('우리는, 함께 믿음의 길을 걷습니다.','We walk this journey together.')}</h1><p>{t('서로 다른 언어, 서로 다른 일상. 예수 그리스도 안에서 하나의 공동체.','Different languages. Different lives. One community in Jesus Christ.')}</p></div><div className="community-layout"><section><div className="community-compose"><div className="avatar"><Heart size={21}/></div><button onClick={()=>setCompose(true)}>{t('오늘의 감사와 기도제목을 나눠주세요.','Share your gratitude or prayer today.')}</button><PenLine size={19}/></div><div className="filter-row"><div className="tabs">{[['all',t('모든 나눔','All stories')],['prayer',t('기도제목','Prayers')],['story',t('은혜나눔','Reflections')]].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}</div></div><SharedFeed key={refresh} category={filter} onCompose={()=>setCompose(true)}/></section><aside><div className="panel community-language"><Globe size={32} strokeWidth={1.2}/><span className="eyebrow">{t("당신의 언어, 당신의 마음","YOUR LANGUAGE, YOUR HEART")}</span><h3>{t('나의 언어로 만나는 우리','Together, in your language')}</h3><p>{t('글쓴이의 이름·국적·작성 언어를 함께 표시합니다. 번역을 제공할 수 없는 경우에는 원문을 그대로 보여드립니다.','Every reflection shows the author’s name, nationality, and writing language. When translation is unavailable, the original stays visible.')}</p><button className="button secondary" onClick={onLanguage}>{languageName(state.language,state.ui)}<Globe size={16}/></button></div><a href="#/qt" className="panel qt-invite"><span className="eyebrow">{t("전 세계가 함께하는 큐티","GLOBAL QUIET TIME")}</span><h3>{t('같은 말씀, 하나의 마음','One Scripture. One heart.')}</h3><p>{t('전 세계 QT에서 함께 묵상해요.','Reflect together in Global QT.')}</p><ArrowUpRight size={22}/></a><p className="tiny muted">{supabase?t('공개 나눔은 검토 후 표시됩니다. 부적절한 내용은 신고하고 원치 않는 사용자는 차단할 수 있습니다.','Public reflections appear after review. You can report inappropriate content and block unwanted contact.'):t('현재는 로컬 개발 체험입니다. 전 세계 공유는 서버 연결 후 제공됩니다.','Local development preview. Worldwide sharing requires the server connection.')}</p></aside></div>{compose&&<Compose onClose={()=>{setCompose(false);setRefresh(n=>n+1);}} onLanguage={onLanguage}/>}</>;
}
