import {ArrowRight,BookOpen,Heart} from 'lucide-react';
import {Cross} from '../components/Ui';
import {useApp} from '../state';
export default function Gospel(){const {t}=useApp();return <><div className="gospel-heading"><Cross/><span className="eyebrow">{t("NCG의 중심","THE HEART OF NCG")}</span><h1>{t('예수 그리스도, 우리의 소망.','Jesus Christ, our living hope.')}</h1><p>{t('하나님께서 우리를 사랑하셔서 예수 그리스도를 보내셨습니다. 예수님은 십자가에서 우리 죄를 담당하시고 죽음에서 부활하셨습니다.','God loved us and sent Jesus Christ. Jesus bore our sins on the cross and rose from the dead.')}</p></div><div className="gospel-steps">{[
 ['01','하나님의 사랑','God’s love','하나님은 우리를 지으시고 사랑하십니다. 그분은 우리를 인격적으로 만나기를 원하십니다.','God made us and loves us. He calls us into a personal relationship with Him.','요한복음 3:16','John 3:16'],
 ['02','우리에게 필요한 구원','Our need for salvation','죄는 하나님과 우리 사이를 가로막습니다. 우리는 스스로의 선행만으로 그 관계를 회복할 수 없습니다.','Sin separates us from God. Our own good works cannot restore that relationship.','로마서 3:23','Romans 3:23'],
 ['03','예수님의 십자가와 부활','The cross and the resurrection','예수 그리스도께서 우리 죄를 대신하여 십자가에서 죽으시고 사흘 만에 다시 살아나셨습니다. 구원은 그분을 믿음으로 받는 하나님의 은혜입니다.','Jesus Christ died on the cross for our sins and rose again on the third day. Salvation is God’s gracious gift, received through faith in Him.','고린도전서 15:3–4 · 에베소서 2:8–9','1 Corinthians 15:3–4 · Ephesians 2:8–9'],
 ['04','믿음으로 응답하는 삶','Responding in faith','죄를 인정하고 하나님께 돌아오며 예수님을 구주와 주님으로 믿으십시오. 말씀과 기도, 예배와 교회 공동체 안에서 그분을 알아가는 길을 함께 걸어갑니다.','Turn to God in repentance and trust Jesus as Savior and Lord. Continue to know Him through Scripture, prayer, worship, and the life of the church.','요한복음 1:12','John 1:12']
 ].map(x=><section key={x[0]}><span>{x[0]}</span><div><h2>{t(x[1],x[2])}</h2><p>{t(x[3],x[4])}</p><small>{t(x[5],x[6])}</small></div></section>)}</div><div className="gospel-next"><BookOpen size={32}/><h2>{t('처음이어도, 함께 걸을 수 있습니다.','Every journey begins with a step.')}</h2><p>{t('새신자 교육에서 하나씩 배우거나, 공동 QT에서 오늘의 말씀을 묵상해보세요.','Begin with the new believer course or reflect on today’s Scripture in Global QT.')}</p><div className="button-row"><a className="button" href="#/school/newcomer">{t('새신자 교육 시작','Begin learning')}<ArrowRight size={17}/></a><a className="button secondary" href="#/qt"><Heart size={17}/>{t('전 세계 QT','Global QT')}</a></div></div></>;}
