import {useEffect,useState} from 'react';
import {BookOpen,Globe,PenLine,Sun,ArrowRight,ChevronLeft,ChevronRight,CalendarDays,Check} from 'lucide-react';
import {useApp} from '../state';
import {translateInterface} from '../core/interface';
import {supabase} from '../auth';
import {Compose} from '../components/Sharing';
import {SharedFeed} from '../components/SharedFeed';
import {QtReminder} from '../components/QtReminder';
import {QtScripture} from '../components/QtScripture';
import {dateInZone,weekDates,shiftDate,qtCopy,qtTopic,formatQtDate,validDate,type QtReading} from '../core/qt';
import {qtScheduleOn,publishedQtOn} from '../core/qt-schedule';
import books from '../data/bible-books.json';

function passageLabel(passage:string,ui:string){const [code,chapter,range]=passage.split('.');const book=books.find(b=>b.code===code);return `${book?translateInterface(book.ko,book.en,ui):code} ${chapter}${range?`:${range}`:''}`;}
export default function QuietTime({onLanguage}:{onLanguage:()=>void}){
 const {state,t,update}=useApp();const [today,setToday]=useState(()=>dateInZone(new Date()));const [selected,setSelected]=useState(()=>{const date=new URLSearchParams(location.hash.split('?')[1]).get('date');return date&&validDate(date)?date:today;});const [week,setWeek]=useState(selected);const [compose,setCompose]=useState(false);const [refresh,setRefresh]=useState(0);const [readings,setReadings]=useState<QtReading[]>([]);const [loading,setLoading]=useState(Boolean(supabase));const [error,setError]=useState(false);const [retry,setRetry]=useState(0);
 const dates=weekDates(week);const first=dates[0];const last=dates[6];
 useEffect(()=>{const refreshToday=()=>setToday(dateInZone(new Date()));const routeDate=()=>{const requested=new URLSearchParams(location.hash.split('?')[1]).get('date');const date=requested&&validDate(requested)?requested:dateInZone(new Date());setSelected(date);setWeek(date);setCompose(false);};const timer=setInterval(refreshToday,60000);document.addEventListener('visibilitychange',refreshToday);window.addEventListener('hashchange',routeDate);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',refreshToday);window.removeEventListener('hashchange',routeDate);};},[]);
 useEffect(()=>{if(!supabase)return;let alive=true;setLoading(true);setReadings([]);setError(false);supabase.from('ncg_qt_readings').select('id,date,passage,section,part,parts,status,translations').eq('status','published').gte('date',first).lte('date',last).order('date').then(({data,error})=>{if(alive){setError(Boolean(error));setReadings((data||[]) as QtReading[]);setLoading(false);}});return()=>{alive=false;};},[first,last,retry]);
 const schedule=qtScheduleOn(selected);const reading=publishedQtOn(readings,selected);const copy=reading?qtCopy(reading,state.language):null;const topic=reading?qtTopic(reading):'';const completion=reading?`qt:${reading.id}`:'';const completed=state.completed.includes(completion);
 function moveWeek(n:number){const next=shiftDate(first,n*7);setWeek(next);setSelected(next);}
 return <>
  <div className="page-heading"><span className="eyebrow">{t("전 세계가 함께하는 큐티","GLOBAL QUIET TIME")}</span><h1>{t('같은 말씀, 서로의 언어로.','One Scripture. Every language.')}</h1><p>{t('말씀을 읽고, 삶에 새기고, 전 세계와 함께 나누어요.','Read the Word, live it out, and reflect with the world.')}</p></div>
  <section className="qt-week" aria-label={t('주간 QT 본문 일정','Weekly QT readings')}><div className="qt-week-heading"><div><span className="eyebrow"><CalendarDays size={15}/> {t('이번 주 말씀 여정','THIS WEEK IN THE WORD')}</span><h2>{formatQtDate(first,state.ui,{month:'short',day:'numeric'})} — {formatQtDate(last,state.ui,{month:'short',day:'numeric'})}</h2></div><div className="button-row"><button className="icon-button" aria-label={t('이전 주','Previous week')} onClick={()=>moveWeek(-1)}><ChevronLeft size={18}/></button><button className="text-link" onClick={()=>{setWeek(today);setSelected(today);}}>{t('오늘','Today')}</button><button className="icon-button" aria-label={t('다음 주','Next week')} onClick={()=>moveWeek(1)}><ChevronRight size={18}/></button></div></div>
   <div className="qt-week-grid">{dates.map(date=>{const item=publishedQtOn(readings,date);const reference=qtScheduleOn(date);const passage=reference?.passage||item?.passage;return <button key={date} aria-pressed={selected===date} onClick={()=>{setSelected(date);setCompose(false);}} className={selected===date?'selected':''}><span className="qt-day-label">{formatQtDate(date,state.ui,{weekday:'short'})}{date===today&&<em>{t('오늘','Today')}</em>}</span><b>{new Date(`${date}T12:00:00Z`).getUTCDate()}</b><span>{passage?passageLabel(passage,state.ui):t('발행 예정','Not published')}</span><small>{item?qtCopy(item,state.language).title:reference?'Duranno · Living Life':'—'}{item&&state.completed.includes(`qt:${item.id}`)&&<Check size={13}/>}</small></button>;})}</div>
   <p className="tiny muted">{t('전 세계가 같은 본문을 읽도록 한국시간(UTC+9) 날짜를 기준으로 합니다.','Shared reading dates follow Korea Standard Time (UTC+9) so the whole world reads the same passage.')}</p>
  </section>
  {schedule&&<p className="tiny muted"><a href={schedule.sourceUrl} target="_blank" rel="noreferrer">{t('본문 출처','Source')}: Duranno · Living Life ↗</a></p>}
  {schedule&&!reading&&<article className="qt-reading"><span className="eyebrow">{t('본문 읽기','Read passage')}</span><h2>{passageLabel(schedule.passage,state.ui)}</h2><QtScripture key={schedule.date} passage={schedule.passage} onLanguage={onLanguage}/></article>}
  {loading?<p role="status">{t('공동 QT 일정을 불러오는 중…','Loading the shared QT schedule…')}</p>:error?<div className="panel" role="alert"><p>{t('QT 일정을 불러오지 못했습니다.','Unable to load the QT schedule.')}</p><button className="button secondary" onClick={()=>setRetry(n=>n+1)}>{t('다시 시도','Try again')}</button></div>:reading&&copy?<>
   <section className="qt-banner"><Sun size={31} strokeWidth={1.3}/><div><b>{formatQtDate(reading.date,state.ui)} · {passageLabel(reading.passage,state.ui)}</b><span>{copy.title}{reading.parts>1&&` · ${t('나누어 읽기','Part')} ${reading.part}/${reading.parts}`}</span></div><span className="pill">{reading.status==='draft'?t('미리보기','PREVIEW'):t("하나의 말씀, 온 세상","ONE WORD. ONE WORLD.")}</span></section>
   <div className="qt-layout"><article className="qt-reading"><span className="eyebrow">01 / {t('말씀을 읽어요','READ THE WORD')}</span><h2>{copy.title}</h2>{reading.parts>1&&<p className="tiny muted">{t('함께 읽는 단락','Shared section')}: {passageLabel(reading.section,state.ui)} · {reading.part}/{reading.parts}</p>}<QtScripture key={reading.id} passage={reading.passage} onLanguage={onLanguage}/>
    <div className="qt-reflect-section"><span className="eyebrow">02 / {t('말씀을 묵상해요','REFLECT')}</span>{copy.language!==state.language.split('-')[0]&&<p className="tiny muted">{t('이 언어의 묵상 안내 번역을 준비하고 있어 영어 안내를 표시합니다.','The reflection guide is shown in English while your language is being prepared.')}</p>}<p lang={copy.language}>{copy.guide}</p><div className="reflection-prompt"><BookOpen size={24}/><h3>{t('오늘, 내 삶에 던지는 질문','A question for your life today')}</h3><p lang={copy.language}>{copy.question}</p></div></div>
    <span className="eyebrow">03 / {t('기도로 응답해요','RESPOND IN PRAYER')}</span><p>{t('말씀을 따라 감사와 회개, 도움을 구하는 기도를 드려보세요. 함께 읽는 이들을 위해서도 기도해주세요.','Respond to Scripture with gratitude, repentance, and a prayer for help. Pray for others reading with you.')}</p><div className="button-row"><button className="button" onClick={()=>setCompose(true)}><PenLine size={17}/>{t('내 묵상 나누기','Share my reflection')}</button><button className="button secondary" aria-pressed={completed} onClick={()=>update(s=>({...s,completed:completed?s.completed.filter(c=>c!==completion):[...s.completed,completion]}))}><Check size={17}/>{completed?t('오늘의 묵상 완료','Reflection completed'):t('묵상 완료하기','Mark as completed')}</button></div>
   </article><aside className="qt-sharing"><QtReminder/><div className="section-head"><div><span className="eyebrow">{t("말씀 안에서 함께","TOGETHER IN THE WORD")}</span><h2>{t('말씀으로 연결되는 우리','Connected by the Word')}</h2></div></div><div className="callout"><Globe size={19}/><span>{supabase?t('같은 본문의 나눔을 함께 읽습니다. 글은 검토 후 공개되며 다른 언어의 원문도 확인할 수 있습니다.','Read reflections on the same passage. Posts appear after review, with the original language available.'):t('현재 나눔은 이 기기에 저장됩니다. 전 세계 공유·번역 서비스를 연결하고 있습니다.','Reflections are currently saved on this device. Global sharing and translation are being connected.')}</span></div><SharedFeed key={`${topic}:${refresh}`} topic={topic} onCompose={()=>setCompose(true)}/></aside></div>
  </>:<div className="panel qt-no-reading"><BookOpen size={32}/><h2>{t('이날의 공동 QT는 아직 발행되지 않았습니다.','No shared QT has been published for this day.')}</h2><p>{t('발행된 날짜를 선택하거나 성경을 펼쳐 읽어보세요.','Choose a published date or open the Bible to read.')}</p><a className="button secondary" href="#/bible">{t('성경 읽기','Read the Bible')}</a></div>}
  {compose&&reading&&<Compose key={topic} topic={topic} onClose={()=>{setCompose(false);setRefresh(n=>n+1);}} onLanguage={onLanguage}/>}
 </>;
}
