import {useState} from 'react';
import {Search,Globe} from 'lucide-react';
import {useApp} from '../state';
import {useVideos} from '../components/useVideos';
import {VideoCard,EmptyVideos} from '../components/Media';
import {languageName} from '../core/languages';
import {Empty} from '../components/Ui';
import type {Video} from '../core/model';
export default function Sermons({onVideo,onLanguage}:{onVideo:(v:Video)=>void;onLanguage:()=>void}){
 const {state,t,update,notify}=useApp();const [search,setSearch]=useState('');const [filter,setFilter]=useState('all');
 const library=useVideos({language:filter==='mine'?state.language:undefined,query:search,saved:filter==='saved'?state.bookmarks:undefined});
 const videos=library.videos;
 return <><div className="page-heading"><span className="eyebrow">{t("모두를 위한 말씀","THE WORD, FOR EVERYONE")}</span><h1>{t('내 언어로 만나는 말씀','The Word, in your language.')}</h1><p>{t('말씀을 듣고, 마음에 새기고, 삶으로 이어가세요.','Listen to the Word. Let it take root. Live it out.')}</p></div><div className="library-toolbar"><label className="search-box"><Search size={19}/><input value={search} maxLength={120} onChange={e=>setSearch(e.target.value)} placeholder={t('제목이나 말씀 내용 검색','Search titles and descriptions')} aria-label={t('말씀 검색','Search messages')}/></label></div><div className="filter-row"><div className="tabs">{[['all',t('전체 말씀','All messages')],['mine',languageName(state.language,state.ui)],['saved',t('보관한 말씀','Saved')]].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)} aria-pressed={filter===id}>{label}</button>)}</div><button className="text-link" onClick={onLanguage}><Globe size={16}/>{t('언어 선택','Choose language')}</button></div>{library.error&&<p className="error" role="alert">{t('교회 영상 목록을 불러오지 못했습니다.','Could not load church videos.')} <button className="text-link" onClick={library.refresh}>{t('다시 시도','Try again')}</button></p>}{library.loading&&!videos.length?<p role="status">{t('말씀을 불러오는 중…','Loading messages…')}</p>:videos.length?<div className="video-grid">{videos.map(v=><VideoCard key={v.id} video={v} onOpen={onVideo}/>)}</div>:search||filter!=='all'?<Empty title={t('아직 이 말씀을 찾지 못했어요.','No messages here yet.')}><p>{t('다른 검색어를 사용하거나 원문 언어의 말씀을 살펴보세요.','Try another search, or explore messages in their original language.')}</p><div className="button-row"><button className="button secondary" onClick={()=>{setFilter('all');setSearch('');}}>{t('전체 말씀 보기','See all messages')}</button>{filter==='mine'&&<button className="button secondary" onClick={()=>{update(s=>({...s,requests:Array.from(new Set([...s.requests,s.language]))}));notify(t('언어 수요가 이 기기에 저장되었습니다. 아직 운영팀에 전송되지는 않습니다.','Language interest saved on this device. It has not been sent to the team.'));}}>{t('이 언어가 필요해요','I need this language')}</button>}</div></Empty>:<EmptyVideos/>}<div className="library-pagination">{library.hasMore&&<button className="button secondary" disabled={library.loading} onClick={()=>void library.more()}>{library.loading?t('불러오는 중…','Loading…'):t('말씀 더 보기','More messages')}</button>}</div><p className="library-note">{t('핵심 말씀 콘텐츠는 누구나 무료로 이용할 수 있습니다.','Core Gospel content is free and open to everyone.')}</p></>;
}
