import {useEffect,useState} from 'react';
import {supabase} from '../auth';
import {dateInZone,qtPassages,type QtReading} from '../core/qt';
import {qtScheduleOn} from '../core/qt-schedule';
import {parsePassage,bibleRequest,type BibleIndex} from '../core/bible';
import {sourceBibleReference} from '../core/bible-source-codes';
export function AdminQt(){
 const [date,setDate]=useState(dateInZone(new Date()));const [rows,setRows]=useState<QtReading[]>([]);const [ranges,setRanges]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');const [reviewed,setReviewed]=useState(false);const current=rows.find(r=>r.date===date);const schedule=qtScheduleOn(date);const [index,setIndex]=useState<BibleIndex|null>(null);
 async function refresh(){const result=await supabase!.from('ncg_qt_readings').select('id,date,passage,passages,section,part,parts,status,translations,published_at').order('date',{ascending:false}).limit(100);if(result.error)setError('QT 일정을 불러오지 못했습니다. 서버 연결과 권한을 확인해주세요.');else setRows(result.data as QtReading[]);}
 useEffect(()=>{void refresh();const c=new AbortController();bibleRequest<BibleIndex>('index',{version:'webp'},c.signal).then(setIndex).catch(()=>setError('성경 장절 검증 정보를 불러오지 못했습니다.'));return()=>c.abort();},[]);
 useEffect(()=>{setNotice('');setReviewed(false);setError('');const r=rows.find(x=>x.date===date);setRanges(r?qtPassages(r).join('\n'):qtScheduleOn(date)?.passages.join('\n')||'');},[date,rows]);
 function validRange(value:string){const p=parsePassage(value);const chapter=index?.books.find(b=>b.id===p?.book)?.chapters.find(c=>Number(c.id)===p?.chapter);return !!(p?.from&&chapter?.verses.some(v=>Number(v.id)===p.from)&&chapter.verses.some(v=>Number(v.id)===p.to));}
 async function save(status:'draft'|'published'){
  if(!supabase||busy)return;setError('');setNotice('');const passages=ranges.split(/\n/).map(v=>v.trim()).filter(Boolean);if(!passages.length||passages.length>10||!passages.every(validRange)){setError('실제 성경에 있는 장절 범위를 입력해주세요. 예: 1CH.20.1-8');return;}
  if(status==='published'&&!reviewed){setError('날짜와 본문 범위를 확인해주세요.');return;}
  // The database retains the original WEBP book codes for published QT records.
  const sourcePassages=passages.map(sourceBibleReference);
  setBusy(true);try{const {error}=await supabase.rpc('ncg_save_qt_reading',{document:{date,passage:sourcePassages[0],passages:sourcePassages,status}});if(error)throw error;await refresh();setNotice(status==='published'?'본문과 나눔 공간을 발행했습니다.':'초안을 저장했습니다.');}catch{setError('저장하지 못했습니다. 발행된 본문은 변경할 수 없으며, 여러 장은 빠진 절 없이 이어져야 합니다. 연결과 관리자 권한도 확인해주세요.');}finally{setBusy(false);}
 }
 return <section className="panel admin-qt"><h2>공동 QT 발행</h2><p className="muted">날짜와 성경 범위만 등록합니다. 제목·묵상 안내·질문은 작성하지 않습니다. 본문 아래에서 함께 묵상을 나눕니다.</p><div className="form-stack"><div className="form-row"><label>발행 날짜 · 한국시간<input type="date" value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></label><label>기존 일정<select value={current?.date||''} onChange={e=>e.target.value&&setDate(e.target.value)}><option value="">새 일정</option>{rows.map(r=><option key={r.id} value={r.date}>{r.date} · {r.passage} · {r.status==='published'?'발행됨':'초안'}</option>)}</select></label></div>{schedule&&<div className="callout"><span>두란노 생명의삶에서 확인한 일정이 있습니다. <a href={schedule.sourceUrl} target="_blank" rel="noreferrer">일정 출처 ↗</a></span><button className="text-link" disabled={Boolean(current?.status==='published')} onClick={()=>{setRanges(schedule.passages.join('\n'));setReviewed(false);}}>확인한 본문 범위 불러오기</button></div>}<label>하루 본문 · 장별로 한 줄<textarea rows={3} value={ranges} onChange={e=>{setRanges(e.target.value.toUpperCase());setReviewed(false);}} placeholder={'1CH.21.18-30\n1CH.22.1-1'}/></label><p className="tiny muted">장절만 저장하며 성경 본문은 독자가 선택한 역본에서 불러옵니다. 여러 장을 읽는 날은 각 장의 범위를 순서대로 넣습니다.</p></div><label className="admin-review-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>날짜와 성경 본문 범위를 확인했습니다.</label><div className="button-row"><button className="button secondary" disabled={busy||!index} onClick={()=>void save('draft')}>초안 저장{current?.status==='published'?' · 발행 취소':''}</button><button className="button" disabled={busy||!index||!reviewed} onClick={()=>void save('published')}>본문과 나눔 발행</button></div>{notice&&<p role="status">{notice}</p>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
