import {useEffect,useState,type FormEvent} from 'react';
import {supabase} from '../auth';
import {dateInZone,previewQtWeek,type QtCopy,type QtReading} from '../core/qt';
import {parsePassage,bibleRequest,type BibleIndex} from '../core/bible';
const empty:QtCopy={title:'',guide:'',question:''};
export function AdminQt(){
 const [date,setDate]=useState(dateInZone(new Date()));const [rows,setRows]=useState<QtReading[]>([]);const [passage,setPassage]=useState('JHN.1.1-5');const [section,setSection]=useState('JHN.1.1-18');const [part,setPart]=useState(1);const [parts,setParts]=useState(3);const [translations,setTranslations]=useState<Record<string,QtCopy>>({ko:{...empty},en:{...empty}});const [lang,setLang]=useState('ko');const [newLang,setNewLang]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');const [reviewed,setReviewed]=useState(false);const current=rows.find(r=>r.date===date);const [index,setIndex]=useState<BibleIndex|null>(null);
 async function refresh(){const result=await supabase!.from('ncg_qt_readings').select('id,date,passage,section,part,parts,status,translations,published_at').order('date',{ascending:false}).limit(100);if(result.error)setError('QT 일정을 불러오지 못했습니다. 002 마이그레이션과 권한을 확인해주세요.');else setRows(result.data as QtReading[]);}
 useEffect(()=>{void refresh();const c=new AbortController();bibleRequest<BibleIndex>('index',{version:'webp'},c.signal).then(setIndex).catch(()=>setError('성경 장절 검증 정보를 불러오지 못했습니다.'));return()=>c.abort();},[]);
 useEffect(()=>{setNotice('');setReviewed(false);const r=rows.find(x=>x.date===date);if(r){setPassage(r.passage);setSection(r.section);setPart(r.part);setParts(r.parts);setTranslations(r.translations);setLang(Object.keys(r.translations)[0]);}else{setTranslations({ko:{...empty},en:{...empty}});setLang('ko');}},[date,rows]);
 function update(field:keyof QtCopy,value:string){setReviewed(false);setTranslations(p=>({...p,[lang]:{...p[lang],[field]:value}}));}
 function usePreview(){const r=previewQtWeek.find(x=>x.date===date)||previewQtWeek[0];setPassage(r.passage);setSection(r.section);setPart(r.part);setParts(r.parts);setTranslations(structuredClone(r.translations));setReviewed(false);setNotice('예시 초안을 불러왔습니다. 날짜와 장절, 모든 언어의 내용을 검수한 뒤 저장하세요.');}
 function validRange(value:string){const p=parsePassage(value);const chapter=index?.books.find(b=>b.id===p?.book)?.chapters.find(c=>Number(c.id)===p?.chapter);return !!(p?.from&&chapter?.verses.some(v=>Number(v.id)===p.from)&&chapter.verses.some(v=>Number(v.id)===p.to));}
 async function save(status:'draft'|'published'){
  if(!supabase||busy)return;setError('');setNotice('');if(!validRange(passage)||!validRange(section)){setError('실제 성경에 있는 장절 범위를 입력해주세요. 예: JHN.1.14-18');return;}
  const p=parsePassage(passage)!,s=parsePassage(section)!;if(p.book!==s.book||p.chapter!==s.chapter||p.from!<s.from!||p.to!>s.to!){setError('하루 본문은 함께 읽는 단락 범위 안에 있어야 합니다.');return;}
  if(!Number.isInteger(part)||!Number.isInteger(parts)||part<1||part>parts||parts>30){setError('분할 회차를 확인해주세요.');return;}
  if(Object.values(translations).some(c=>!c.title.trim()||!c.guide.trim()||!c.question.trim())){setError('각 언어의 제목, 묵상 안내, 질문을 모두 입력해주세요.');return;}
  if(status==='published'&&!reviewed){setError('발행 전 검수 확인이 필요합니다.');return;}
  setBusy(true);try{const {error}=await supabase.rpc('ncg_save_qt_reading',{document:{date,passage,section,part,parts,translations,status}});if(error)throw error;await refresh();setNotice(status==='published'?'공동 QT가 발행되었습니다.':'초안을 저장했습니다.');}catch{setError('저장하지 못했습니다. 발행된 본문 범위는 변경할 수 없습니다. 연결과 관리자 권한도 확인해주세요.');}finally{setBusy(false);}
 }
 function addLanguage(e:FormEvent){e.preventDefault();const code=newLang.trim();if(!/^[a-zA-Z]{2,8}(-[a-zA-Z0-9]{1,8})*$/.test(code)){setError('언어 코드를 입력해주세요. 예: en, ko, th, ar');return;}setTranslations(p=>({...p,[code]:p[code]||{...empty}}));setLang(code);setNewLang('');setReviewed(false);}
 return <section className="panel admin-qt"><h2>공동 QT 발행</h2><p className="muted">날짜와 장절은 전 세계에 공통으로 적용됩니다. 성경 본문을 이곳에 번역해 입력하지 않고, 정식 역본에서 불러옵니다. 검수한 묵상 안내만 언어별로 등록하세요.</p><div className="form-stack"><div className="form-row"><label>발행 날짜 · 한국시간<input type="date" value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></label><label>기존 일정<select value={current?.date||''} onChange={e=>e.target.value&&setDate(e.target.value)}><option value="">새 일정</option>{rows.map(r=><option key={r.id} value={r.date}>{r.date} · {r.passage} · {r.status==='published'?'발행됨':'초안'}</option>)}</select></label></div><div className="form-row"><label>하루 본문 · USFM<input value={passage} onChange={e=>{setPassage(e.target.value.toUpperCase());setReviewed(false);}} placeholder="JHN.1.14-18"/></label><label>전체 소제목 단락<input value={section} onChange={e=>{setSection(e.target.value.toUpperCase());setReviewed(false);}} placeholder="JHN.1.1-18"/></label></div><div className="form-row"><label>이번 회차<input type="number" min={1} max={30} value={part} onChange={e=>{setPart(Number(e.target.value));setReviewed(false);}}/></label><label>전체 나눔 횟수<input type="number" min={1} max={30} value={parts} onChange={e=>{setParts(Number(e.target.value));setReviewed(false);}}/></label></div><button className="text-link" onClick={usePreview}>요한복음 예시 초안 불러오기</button><div className="tabs">{Object.keys(translations).map(code=><button key={code} className={lang===code?'active':''} onClick={()=>setLang(code)}>{code}</button>)}</div><label>제목 · {lang}<input value={translations[lang]?.title||''} maxLength={160} onChange={e=>update('title',e.target.value)}/></label><label>묵상 안내 · {lang}<textarea rows={4} maxLength={5000} value={translations[lang]?.guide||''} onChange={e=>update('guide',e.target.value)}/></label><label>적용 질문 · {lang}<textarea rows={2} maxLength={1000} value={translations[lang]?.question||''} onChange={e=>update('question',e.target.value)}/></label></div><form className="admin-add-language" onSubmit={addLanguage}><input aria-label="추가할 언어 코드" placeholder="추가 언어 코드 · th, ar…" value={newLang} onChange={e=>setNewLang(e.target.value)}/><button className="button secondary" type="submit">언어 추가</button></form><label className="admin-review-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>날짜, 본문 범위, 모든 언어의 묵상 안내를 교회에서 검수했습니다.</label><div className="button-row"><button className="button secondary" disabled={busy||!index} onClick={()=>void save('draft')}>초안 저장{current?.status==='published'?' · 발행 취소':''}</button><button className="button" disabled={busy||!index||!reviewed} onClick={()=>void save('published')}>검수한 QT 발행</button></div>{notice&&<p role="status">{notice}</p>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
