import {useState,type FormEvent} from 'react';
import {ArrowRight,Mail,ShieldCheck} from 'lucide-react';
import {supabase,useAuth} from '../auth';
import {useApp} from '../state';

export function AuthPanel(){
 const {t}=useApp();const {configured,loading}=useAuth();
 const [email,setEmail]=useState('');const [token,setToken]=useState('');const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [signup,setSignup]=useState(false);
 const redirectTo=new URL(location.pathname==='/admin.html'?'/admin.html':'/auth/callback',location.origin).href;
 async function google(){if(!supabase)return;setBusy(true);setError('');try{const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo}});if(error)throw error;}catch{setError(t('Google 로그인에 연결하지 못했습니다. 잠시 후 다시 시도해주세요.','Could not connect to Google sign-in. Please try again.'));setBusy(false);}}
 async function emailLogin(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');try{const {error}=await supabase.auth.signInWithOtp({email:email.trim(),options:{shouldCreateUser:signup,emailRedirectTo:redirectTo}});if(error)throw error;setSent(true);}catch{setError(t('인증 메일을 보내지 못했습니다. 이메일 주소와 가입 여부를 확인하거나 잠시 후 다시 시도해주세요.','Unable to send the email. Check your address or try again later.'));}finally{setBusy(false);}}
 async function verify(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');try{const {error}=await supabase.auth.verifyOtp({email:email.trim(),token:token.trim(),type:'email'});if(error)throw error;}catch{setError(t('인증 코드가 올바르지 않거나 만료되었습니다.','The code is invalid or has expired.'));}finally{setBusy(false);}}
 return <section className="auth-card"><div className="auth-intro"><span className="eyebrow">{t("NCG에 오신 것을 환영합니다","WELCOME TO NCG")}</span><h2>{t('믿음의 여정을, 함께 이어가요.','Continue your journey, together.')}</h2><p>{t('내 묵상과 배움을 모으고, 세계의 친구들과 연결되세요.','Keep your reflections and learning together. Connect with friends around the world.')}</p><ShieldCheck size={30} strokeWidth={1.3}/><small>{t('말씀과 교육은 로그인 없이도 볼 수 있습니다.','Scripture and lessons are open without signing in.')}</small></div><div className="auth-form"><div className="tabs"><button className={!signup?'active':''} onClick={()=>{setSignup(false);setSent(false);setError('');}}>{t('로그인','Sign in')}</button><button className={signup?'active':''} onClick={()=>{setSignup(true);setSent(false);setError('');}}>{t('회원가입','Join NCG')}</button></div>{!configured&&<p className="callout" role="status">{t('회원 서비스를 준비하고 있습니다. 인증 서버 연결 후 Google·이메일로 이용할 수 있습니다.','Member services are being prepared. Google and email sign-in will be available after setup.')}</p>}<button className="button google-button" disabled={!configured||loading||busy} onClick={google}><span aria-hidden="true" className="google-letter">G</span>{t('Google로 계속하기','Continue with Google')}</button><div className="auth-divider"><span>{t('또는 이메일','or email')}</span></div>{!sent?<form className="form-stack" onSubmit={emailLogin}><label>{t('이메일 주소','Email address')}<input type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><button className="button" disabled={!configured||busy}>{busy?t('전송 중…','Sending…'):t('인증 메일 보내기','Send sign-in email')}<Mail size={17}/></button><small className="muted">{t('메일로 본인을 확인합니다. 비밀번호를 만들지 않아도 됩니다.','Verify through your inbox. No password to remember.')}</small></form>:<><p role="status">{t('인증 메일이 발송되었다면 받은 편지함의 링크를 열어주세요. 인증 코드가 있는 경우 아래에 입력할 수 있습니다.','If an email was sent, open the link in your inbox. If it includes a code, you can enter it below.')}</p><form className="form-stack" onSubmit={verify}><label>{t('이메일 인증 코드','Email verification code')}<input autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6,8}" minLength={6} maxLength={8} value={token} onChange={e=>setToken(e.target.value.replace(/\D/g,''))} required/></label><button className="button" disabled={busy||token.length<6}>{t('인증하고 계속','Verify and continue')}<ArrowRight size={17}/></button></form><button className="text-link" onClick={()=>setSent(false)}>{t('다른 이메일 사용 / 다시 요청','Use another email / request again')}</button></>}{error&&<p className="error" role="alert">{error}</p>}</div></section>;
}
