import {lazy,Suspense,useState,type FormEvent} from 'react';
import {Play,Bookmark,ExternalLink,Globe,Plus} from 'lucide-react';
import {parseMedia,mediaEmbed} from '../core/media';
import type {Video} from '../core/model';
import {useApp} from '../state';
import {Modal,Empty} from './Ui';
import {languageName} from '../core/languages';
const LanguagePicker=lazy(()=>import('./LanguagePicker'));

export function VideoCard({video,onOpen}:{video:Video;onOpen:(v:Video)=>void}){
 const {state,update,t}=useApp();const media=parseMedia(video.url);const saved=state.bookmarks.includes(video.id);
 return <article className="video-card"><button className="video-cover" onClick={()=>onOpen(video)} aria-label={t('재생: ','Play: ')+video.title}>{!state.lowData&&media?.kind==='youtube'?<img src={`https://i.ytimg.com/vi/${media.id}/hqdefault.jpg`} alt="" loading="lazy" width="480" height="360"/>:<div className="video-placeholder"><Play size={40}/></div>}<span className="play-circle"><Play size={19} fill="currentColor"/></span><span className="image-label">{languageName(video.language,state.ui)}</span></button><div className="video-info"><span className="eyebrow">{video.category==='worship'?t("예배","WORSHIP"):t("말씀","MESSAGE")}</span><button className="plain title-button" onClick={()=>onOpen(video)}><h3>{video.title}</h3></button><div className="video-meta"><span>{video.official?(video.speaker||t('새빛교회','Newlight Church')):t('기기에 등록한 영상','Saved on this device')}</span><button className={`icon-button ${saved?'saved':''}`} aria-label={saved?t('보관 해제','Remove bookmark'):t('말씀 보관','Save message')} aria-pressed={saved} onClick={()=>update(s=>({...s,bookmarks:s.bookmarks.includes(video.id)?s.bookmarks.filter(id=>id!==video.id):[...s.bookmarks,video.id]}))}><Bookmark size={18} fill={saved?'currentColor':'none'}/></button></div></div></article>;
}
export function VideoPlayer({video,onClose}:{video:Video;onClose:()=>void}){
 const {state,t}=useApp();const [playing,setPlaying]=useState(false);const [failed,setFailed]=useState(false);const media=parseMedia(video.url);
 return <Modal wide title={video.title} onClose={onClose}><div className="player">{!playing?<button className="player-start" onClick={()=>setPlaying(true)}><span className="play-circle"><Play size={28} fill="currentColor"/></span>{t('영상 재생','Play video')}<small>{t('재생을 누르면 영상 서비스에 연결됩니다.','Connects to the video provider when you play.')}</small></button>:media?.kind==='youtube'?<iframe title={video.title} src={mediaEmbed(media,state.language)} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>:media?.kind==='file'?<video src={media.url} controls autoPlay playsInline onError={()=>setFailed(true)}/>:null}</div>{failed&&<p className="error" role="alert">{t('영상 파일에 연결하지 못했습니다. 주소와 접근 권한을 확인해주세요.','Could not load this file. Check the URL and access permissions.')}</p>}<p className="tiny muted">{video.speaker}{video.speaker&&video.scripture?' · ':''}{video.scripture}{video.recordedOn?' · '+video.recordedOn:''}</p><p className="muted">{video.description||t('말씀과 함께하는 시간을 가져보세요.','Take a moment with the Word.')}</p><div className="callout"><Globe size={19}/><span>{t('자막은 영상에 제공된 언어만 이용할 수 있습니다. 자동 번역의 정확성과 제공 여부는 영상 서비스에 따라 달라집니다.','Captions depend on the languages available for this video. Availability and accuracy vary by provider.')}</span></div>{media&&<a className="button secondary" href={media.url} target="_blank" rel="noreferrer">{t('원본에서 열기','Open original')}<ExternalLink size={16}/></a>}</Modal>;
}
export function AddVideo({onClose,category='sermon'}:{onClose:()=>void;category?:Video['category']}){
 const {state,update,t,notify}=useApp();const [url,setUrl]=useState('');const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [lang,setLang]=useState(state.language);const [kind,setKind]=useState(category);const [error,setError]=useState('');const [pick,setPick]=useState(false);
 function submit(e:FormEvent){e.preventDefault();const media=parseMedia(url);if(!media){setError(t('유효한 YouTube 영상 링크 또는 HTTPS MP4/WebM 주소를 입력해주세요.','Enter a valid YouTube video link or HTTPS MP4/WebM URL.'));return;}if(!title.trim()){setError(t('영상 제목을 입력해주세요.','Please enter a title.'));return;}if(state.videos.some(v=>v.url===media.url)){setError(t('이미 등록된 영상입니다.','This video is already in your library.'));return;}const v:Video={id:crypto.randomUUID(),title:title.trim(),description:description.trim(),language:lang,category:kind,url:media.url,createdAt:new Date().toISOString()};update(s=>({...s,videos:[v,...s.videos]}));notify(t('영상이 이 기기에 등록되었습니다.','Video saved on this device.'));onClose();}
 return <><Modal title={t('영상 링크 등록','Add a video link')} onClose={onClose}><p className="muted">{t('현재는 이 브라우저에 저장됩니다. 회원 전체에게 공개되지는 않습니다.','Saved in this browser. It is not published to other members.')}</p><form onSubmit={submit} className="form-stack"><label>{t('YouTube 또는 직접 호스팅 영상 주소','YouTube or hosted video URL')}<input required value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://www.youtube.com/watch?v=…" maxLength={2000}/></label><label>{t('제목','Title')}<input value={title} required maxLength={160} onChange={e=>setTitle(e.target.value)}/></label><label>{t('설명','Description')}<textarea value={description} maxLength={2000} rows={3} onChange={e=>setDescription(e.target.value)}/></label><div className="form-row"><label>{t('분류','Category')}<select value={kind} onChange={e=>setKind(e.target.value as Video['category'])}><option value="sermon">{t('설교 · 말씀','Sermon / message')}</option><option value="worship">{t('온라인 예배','Online worship')}</option></select></label><div><span className="field-label">{t('영상 언어','Video language')}</span><button type="button" className="select-button" onClick={()=>setPick(true)}><Globe size={16}/>{languageName(lang,state.ui)}</button></div></div>{error&&<p className="error" role="alert">{error}</p>}<button className="button" type="submit"><Plus size={17}/>{t('영상 등록','Add video')}</button></form></Modal>{pick&&<Suspense><LanguagePicker onClose={()=>setPick(false)} onSelect={setLang}/></Suspense>}</>;
}
export function EmptyVideos({onAdd}:{onAdd:()=>void}){const {t}=useApp();return <Empty title={t('말씀을 만나는 첫 연결','Your first connection to the Word')}><p>{t('YouTube 링크를 등록하면 여기에서 바로 찾고 시청할 수 있어요.','Add a YouTube link to find and watch it here.')}</p><button className="button secondary" onClick={onAdd}><Plus size={17}/>{t('영상 링크 등록','Add a video')}</button></Empty>;}
