import {useEffect,useState} from 'react';
import {BookOpen,Globe,ArrowRight} from 'lucide-react';
import {useApp} from '../state';
import {bibleRequest,preferredBibleVersion,koreanRevisedLink,webVersion,safeBibleLink,type BiblePassage,type BibleVersion} from '../core/bible';
import {languageName} from '../core/languages';
export function QtScripture({passage,onLanguage}:{passage:string;onLanguage:()=>void}){
 const {state,t}=useApp();const [versions,setVersions]=useState<BibleVersion[]>([]);const [versionId,setVersionId]=useState('');const [text,setText]=useState<BiblePassage|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [fallback,setFallback]=useState(false);const [retry,setRetry]=useState(0);
 useEffect(()=>{const c=new AbortController();setVersions([]);setVersionId('');setText(null);setError('');setLoading(true);setFallback(false);
  bibleRequest<{data:BibleVersion[]}>('versions',{language:state.language},c.signal).then(r=>{if(!c.signal.aborted){setVersions(r.data);setVersionId(preferredBibleVersion(r.data,state.language)?.id||'');}}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();
 },[state.language,retry]);
 useEffect(()=>{if(!versionId)return;const c=new AbortController();setText(null);setError('');setLoading(true);bibleRequest<BiblePassage>('passage',{version:versionId,passage},c.signal).then(r=>{if(!c.signal.aborted)setText(r);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[versionId,passage,retry]);
 const version=versions.find(v=>v.id===versionId);const source=safeBibleLink(version?.publisher_url);
 function readEnglish(){setFallback(true);setVersions([webVersion]);setVersionId('webp');}
 return <div className="qt-scripture"><div className="qt-scripture-tools"><button className="text-link" onClick={onLanguage}><Globe size={16}/>{languageName(state.language,state.ui)}</button><label><span className="sr-only">{t('QT 성경 역본','QT Bible version')}</span><select value={versionId} disabled={!versions.length} onChange={e=>setVersionId(e.target.value)}>{!versions.length&&<option value="">{t('역본 연결 대기','Version pending')}</option>}{versions.map(v=><option value={v.id} key={v.id}>{v.localized_title||v.title}</option>)}</select></label></div>
 {fallback&&<p className="tiny muted">{t('선택하신 WEB 영어 원문을 표시합니다. 메뉴 언어는 유지됩니다.','Showing the WEB English text you selected. Your interface language stays the same.')}</p>}
 {loading?<p role="status">{t('성경 본문을 불러오는 중…','Loading Scripture…')}</p>:error||!text?<div className="qt-text-pending"><BookOpen size={28}/><p>{!versions.length?t('이 언어의 정식 성경 역본을 연결하고 있습니다. 같은 장절을 아래에서 읽을 수 있습니다.','A licensed Bible in your language is being connected. You can read the same passage below.'):t('본문을 불러오지 못했습니다. 연결을 확인해주세요.','Unable to load the passage. Please check your connection.')}</p><div className="button-row">{state.language.split('-')[0]==='ko'&&<a className="button secondary" href={koreanRevisedLink(passage)} target="_blank" rel="noreferrer">{t('대한성서공회에서 개역개정 읽기','Read NKRV at the Korean Bible Society')} ↗</a>}{!versions.length&&<button className="button secondary" onClick={readEnglish}>{t('WEB 영어 성경으로 읽기','Read the WEB in English')}</button>}<a className="text-link" href="https://www.bible.com/languages" target="_blank" rel="noreferrer">{t('내 언어 성경 찾기','Find my language on YouVersion')} ↗</a>{error&&error!=='bible_not_configured'&&<button className="text-link" onClick={()=>setRetry(n=>n+1)}>{t('다시 시도','Retry')}</button>}</div></div>:<><div className="qt-scripture-text" lang={version?.language_tag} dir="auto">{text.verses?text.verses.map(v=><div key={v.id}><p><sup>{v.number}</sup><span>{v.text}</span></p>{v.notes?.length&&<details className="verse-notes"><summary>{t('각주','Notes')} {v.number}</summary>{v.notes.map((n,i)=><p key={i}>{n}</p>)}</details>}</div>):<p className="provider-scripture">{text.content}</p>}</div><div className="qt-text-credit"><b>{text.reference} · {version?.abbreviation}</b><p>{version?.copyright}</p>{source&&<a href={source} target="_blank" rel="noreferrer">{t('본문 출처 및 이용 안내','Source and permissions')} ↗</a>}</div></>}
 <a className="text-link qt-open-bible" href={`#/bible?passage=${encodeURIComponent(passage)}&language=${encodeURIComponent(version?.language_tag||state.language)}&version=${encodeURIComponent(versionId)}`}><BookOpen size={17}/>{t('성경에서 이어 읽기','Continue in the Bible')}<ArrowRight size={16}/></a></div>;
}
