import {useEffect,useRef,useId,type ReactNode} from 'react';
import {ArrowUpRight,Globe,Camera,Play,X} from 'lucide-react';
import {useApp} from '../state';
import {church} from '../data/church';

export function Cross({className=''}:{className?:string}){return <img className={`church-symbol ${className}`} src="/brand/newlight-symbol.png" alt="" aria-hidden="true"/>;}
export function Brand(){const {t}=useApp();return <a href="#/" className="brand" aria-label={t('NCG 홈','NCG Home')}><img className="brand-wordmark" src="/brand/ncg-wordmark.svg" width="604" height="252" alt="NCG · NEWLIGHT CHURCH GLOBAL"/></a>;}
export function SectionTitle({eyebrow,title,link,href}:{eyebrow:string;title:string;link?:string;href?:string}){return <div className="section-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{link&&<a className="text-link" href={href}>{link}<ArrowUpRight size={16}/></a>}</div>;}
export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null);const {t}=useApp();const titleId=useId();
 useEffect(()=>{const previous=document.activeElement as HTMLElement;ref.current?.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow;previous?.focus();};},[]);
 return <dialog ref={ref} className={`modal ${wide?'wide':''}`} onCancel={e=>{e.preventDefault();onClose();}} aria-labelledby={titleId} onClick={e=>{if(e.target===ref.current){const r=ref.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}}><div className="modal-heading"><h2 id={titleId}>{title}</h2><button type="button" className="icon-button" onClick={onClose} aria-label={t('닫기','Close')}><X size={21}/></button></div>{children}</dialog>;
}
export function Empty({title,children}:{title:string;children:ReactNode}){return <div className="empty-state"><Cross/><h3>{title}</h3>{children}</div>;}
export function Footer(){const {t}=useApp();return <footer><div><a className="footer-contact" href="#/contact">{t('문의하기','Contact')}<ArrowUpRight size={14}/></a><b>One Gospel. Every Nation. Every Language.</b><p>{t('대한예수교장로회(합동) 경기동중노회 · 새빛교회','Newlight Church · Gyeonggi Dongjung Presbytery · Presbyterian Church in Korea (Hapdong)')}</p><p>{t(church.address,church.englishAddress)}</p><p><a href={"mailto:"+church.email}>{church.email}</a></p><nav className="footer-sites" aria-label={t('새빛교회 공식 채널','Newlight Church official channels')}><a href={church.website} target="_blank" rel="noopener noreferrer"><Globe size={17}/>{t('새빛교회 홈페이지','Newlight Church website')}</a><a href={church.youtube} target="_blank" rel="noopener noreferrer"><Play size={18}/>{t('유튜브','YouTube')}</a><a href={church.instagram} target="_blank" rel="noopener noreferrer"><Camera size={17}/>{t('인스타그램','Instagram')}</a></nav></div><span>© 2026 {t('새빛교회','Newlight Church')}<br/>{t("NCG 자체 제작 콘텐츠","NCG original content")}</span></footer>;}
