import spanishQt from '../data/qt/es.json';
export const QT_TIME_ZONE='Asia/Seoul';
export type QtCopy={title:string;guide:string;question:string};
export type QtReading={id:string;date:string;passage:string;section:string;part:number;parts:number;status:'draft'|'published';translations:Record<string,QtCopy>};
export function dateInZone(now:Date,timeZone=QT_TIME_ZONE){
 const parts=new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);
 const part=(type:string)=>parts.find(p=>p.type===type)?.value;
 return `${part('year')}-${part('month')}-${part('day')}`;
}
export function validDate(value:string){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value;}
export function shiftDate(value:string,days:number){if(!validDate(value))throw Error('invalid_date');const d=new Date(`${value}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
export function weekDates(value:string){if(!validDate(value))throw Error('invalid_date');const weekday=new Date(`${value}T12:00:00Z`).getUTCDay();const monday=shiftDate(value,-((weekday+6)%7));return Array.from({length:7},(_,i)=>shiftDate(monday,i));}
export function qtTopic(reading:QtReading){return `qt:${reading.id}`;}
export function qtCopy(reading:QtReading,language:string){const base=language.split('-')[0];const lang=reading.translations[language]?language:reading.translations[base]?base:reading.translations.en?'en':Object.keys(reading.translations)[0];return {language:lang,...reading.translations[lang]};}
export function formatQtDate(value:string,locale:string,options:Intl.DateTimeFormatOptions={month:'short',day:'numeric',weekday:'short'}){return new Intl.DateTimeFormat(locale,{...options,timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`));}

// Editorial sample only. Public publication requires a reviewed record on the server.
const previewDrafts:QtReading[]=[
 {id:'preview-2026-09-21',date:'2026-09-21',passage:'JHN.1.1-5',section:'JHN.1.1-18',part:1,parts:3,status:'draft',translations:{ko:{title:'태초에 계신 말씀',guide:'말씀은 태초부터 하나님과 함께 계셨고 하나님이십니다. 만물의 창조와 생명이 그분께 있음을 살펴보세요.',question:'내 삶의 시작과 방향을 예수 그리스도께 맡긴다는 것은 오늘 어떤 모습일까요?'},en:{title:'The Word in the beginning',guide:'The Word was with God in the beginning and is God. Notice how creation and life belong to him.',question:'What would it look like today to entrust the direction of your life to Jesus Christ?'}}},
 {id:'preview-2026-09-22',date:'2026-09-22',passage:'JHN.1.6-13',section:'JHN.1.1-18',part:2,parts:3,status:'draft',translations:{ko:{title:'참빛을 영접하는 사람들',guide:'요한은 자신이 빛이 아니라 빛을 증언하는 사람임을 밝힙니다. 예수님을 영접하고 그 이름을 믿는 이들에게 주시는 은혜를 읽어보세요.',question:'나 자신을 드러내기보다 예수님을 가리킬 수 있는 자리는 어디인가요?'},en:{title:'Receiving the true light',guide:'John is a witness to the light, not the light himself. Read about the grace given to those who receive Jesus and believe in his name.',question:'Where can you point to Jesus rather than draw attention to yourself?'}}},
 {id:'preview-2026-09-23',date:'2026-09-23',passage:'JHN.1.14-18',section:'JHN.1.1-18',part:3,parts:3,status:'draft',translations:{ko:{title:'우리 가운데 오신 말씀',guide:'말씀이 육신이 되어 우리 가운데 거하셨습니다. 예수 그리스도 안에서 드러난 하나님의 은혜와 진리를 천천히 묵상해보세요.',question:'우리에게 가까이 오신 예수님의 은혜를 기억하며, 오늘 누구에게 사랑을 실천할 수 있을까요?'},en:{title:'The Word dwelling among us',guide:'The Word became flesh and dwelt among us. Reflect on God’s grace and truth revealed in Jesus Christ.',question:'Remembering the grace of Jesus who came near to us, whom can you love in a practical way today?'}}},
 {id:'preview-2026-09-24',date:'2026-09-24',passage:'JHN.1.19-28',section:'JHN.1.19-28',part:1,parts:1,status:'draft',translations:{ko:{title:'주님의 길을 준비하는 증언',guide:'자신이 누구냐는 질문 앞에서 요한은 그리스도께 시선을 돌립니다. 그의 정직하고 겸손한 증언을 살펴보세요.',question:'내가 맡은 역할에서 예수님이 중심이 되도록 내려놓을 것은 무엇인가요?'},en:{title:'A witness preparing the way',guide:'Asked who he is, John turns attention toward the Christ. Notice the honesty and humility of his witness.',question:'What can you set aside so that Jesus remains central in the role you have been given?'}}},
 {id:'preview-2026-09-25',date:'2026-09-25',passage:'JHN.1.29-34',section:'JHN.1.29-34',part:1,parts:1,status:'draft',translations:{ko:{title:'세상 죄를 지시는 하나님의 어린양',guide:'요한이 가리킨 예수님은 세상 죄를 지시는 하나님의 어린양입니다. 우리를 위해 십자가를 지신 구주를 바라보세요.',question:'나의 죄와 염려를 구주께 맡기며 오늘 어떤 감사의 기도를 드리겠습니까?'},en:{title:'The Lamb of God',guide:'John points to Jesus as the Lamb of God who takes away the sin of the world. Look to the Savior who bore the cross for us.',question:'As you entrust your sin and cares to the Savior, what prayer of gratitude will you offer today?'}}},
 {id:'preview-2026-09-26',date:'2026-09-26',passage:'JHN.1.35-42',section:'JHN.1.35-42',part:1,parts:1,status:'draft',translations:{ko:{title:'와서 보라',guide:'예수님을 만난 제자들은 그분과 함께 머물고 다른 사람을 그분께 데려옵니다. 말씀 속에서 예수님의 초대에 귀 기울여보세요.',question:'오늘 주님과 함께 머무를 시간을 어떻게 마련하고, 누구를 위해 기도할까요?'},en:{title:'Come and see',guide:'The disciples meet Jesus, stay with him, and bring others to him. Listen to his invitation in this passage.',question:'How will you make time to be with the Lord today, and for whom will you pray?'}}},
 {id:'preview-2026-09-27',date:'2026-09-27',passage:'JHN.1.43-51',section:'JHN.1.43-51',part:1,parts:1,status:'draft',translations:{ko:{title:'나를 따르라',guide:'예수님은 빌립을 부르시고 나다나엘을 아십니다. 나를 아시는 주님의 부르심 앞에서 믿음으로 응답해보세요.',question:'예수님을 따르는 믿음을 오늘의 작은 선택에 어떻게 담을 수 있나요?'},en:{title:'Follow me',guide:'Jesus calls Philip and knows Nathanael. Consider your response in faith to the Lord who knows you.',question:'How can faith in Jesus shape a small choice you will make today?'}}},
];

export const previewQtWeek:QtReading[]=previewDrafts.map(reading=>({...reading,translations:{...reading.translations,...((spanishQt as Record<string,QtCopy>)[reading.date]?{es:(spanishQt as Record<string,QtCopy>)[reading.date]}:{})}}));
